### ISSUE TITLE
openstack_neutron_network_ip_availabilities_* metrics have an empty project_id on older versions of OpenStack

### ISSUE THREAD

**Issue by mchlumsky** [openstack-exporter/openstack-exporter#100]
On older openstack clouds (Newton and older have the issue. Queens and newer do not have this issue), openstack_neutron_network_ip_availabilities_* metrics have an empty project_id.

For example:
`openstack_neutron_network_ip_availabilities_used{cidr="x.x.x.x/24",ip_version="4",network_id="xxxx",network_name="some_network",project_id="",subnet_name="some_subnet"} 113`

This is almost certainly because older clouds return the project_id in a tenant_id field.
Relevant output  when running `openstack ip availability show <network-id> --debug` on older clouds.
```
REQ: curl -g -i -X GET https://xxx:9696/v2.0/network-ip-availabilities/xxx -H "User-Agent: openstacksdk/0.46.0 keystoneauth1/4.0.0 python-requests/2.23.0 CPython/3.8.3" -H "X-Auth-Token: {SHA256}xxx"
https://xxx:9696 "GET /v2.0/network-ip-availabilities/xxx HTTP/1.1" 200 401
RESP: [200] content-length: 401 content-type: application/json date: Tue, 16 Jun 2020 15:38:01 GMT x-openstack-request-id: req-4d1ba1f0-c4d3-461e-b1dc-f552016a7d97
RESP BODY: {"network_ip_availability": {"used_ips": 6, "subnet_ip_availability": [{"used_ips": 6, "subnet_id": "xxx", "subnet_name": "xxx", "ip_version": 4, "cidr": "192.168.1.0/24", "total_ips": 240}], "network_id": "xxxx", "tenant_id": "xxx", "total_ips": 240, "network_name": "xxx"}}
```

**Comment by niedbalski** [comment]
@mchlumsky thank you for this great bug report. I have added a fallback to tenant_id if project_id isn't present in the networkipavailabilities. Please check #101

**Comment by mchlumsky** [comment]
@niedbalski Thanks for the quick response. Much appreciated!
