### ISSUE TITLE
need to help about `--collect-metric-time`

### ISSUE THREAD

**Issue by bientt210** [openstack-exporter/openstack-exporter#107]
Hi Everyone,

when I start as a service, I got an error 
**i/o timeout" source="main.go:63"**
So, someone help me if I using option `--collect-metric-time` Is it could be resolve my problem? If I set --collect-metric-time="5m" as I know is 5 minutes, but my service went fail. can someone hep me in this stuation?

Thanks for your support

**Comment by niedbalski** [comment]
Hello @bientt210 

* Can you please pastebin the full debug log? , also the full parameters that you used in the exporter?

Thanks,

**Comment by bientt210** [comment]
Thanks for answer me @niedbalski,
When I run with debug mode: **./openstack-exporter --log.level="debug" --os-client-config="/etc/openstack/clouds.yaml" openstack**

Here the log:
**INFO[0000] Starting openstack exporter version (version=1.1.0, branch=HEAD, revision=f60affb67206e1ab66456b527f3ffc3f8e2a74c6) for cloud: openstack  source="main.go:49"
INFO[0000] Build context (go=go1.13.12, user=root@15b7eb12a7c5, date=20200702-16:24:38)  source="main.go:50"
ERRO[0030] enabling exporter for service compute failed: Post https://domain-name/identity/v3/auth/tokens: dial tcp ip-address:443: i/o timeout  source="main.go:63"
ERRO[0060] enabling exporter for service image failed: Post https://domain-name/identity/v3/auth/tokens: dial tcp ip-address:443: i/o timeout  source="main.go:63"
ERRO[0090] enabling exporter for service volume failed: Post https://domain-name/identity/v3/auth/tokens: dial tcp ip-address:443: i/o timeout  source="main.go:63"
ERRO[0120] enabling exporter for service object-store failed: Post https://domain-name/identity/v3/auth/tokens: dial tcp ip-address:443: i/o timeout  source="main.go:63"
ERRO[0150] enabling exporter for service network failed: Post https://domain-name/identity/v3/auth/tokens: dial tcp ip-address:443: i/o timeout  source="main.go:63"
ERRO[0180] enabling exporter for service load-balancer failed: Post https://domain-name/identity/v3/auth/tokens: dial tcp ip-address:443: i/o timeout  source="main.go:63"
ERRO[0210] enabling exporter for service container-infra failed: Post https://domain-name/identity/v3/auth/tokens: dial tcp ip-address:443: i/o timeout  source="main.go:63"**

Thanks you for support me!

**Comment by bientt210** [comment]
Thanks for answer me @niedbalski ,

My problem has solved, cause be network connection. i'm close issue now,
Thanks you so much for your support :)
