### ISSUE TITLE
New metrics: Instance details and status, volume details and status.

### ISSUE THREAD

**Issue by vaibhavjayas** [openstack-exporter/openstack-exporter#11]
I need some new metrics like 
instance name status volume names status 
flavor names

can you help

**Comment by niedbalski** [comment]
@vaibhavjayas 

Thank you for your report. So, just to clarify, the metrics you are asking for are:

* Instance name, id, status
* Volume name, id, status

Would this be for all tenants or just the admin tenant? Currently the exporter doesn't supports
per tenant resources.

Thanks for any further clarification on your request.

**Comment by vaibhavjayas** [comment]
yes if this can be tenant wide it would be of great help 
also the metrics are 
1) for volumes if we can have availability_zone,id,name,size,status
2)Instance name, id, status,

**Comment by niedbalski** [comment]
@vaibhavjayas 

I've committed a change to include the server_status metrics with most of the instance fields, could you please try the master docker image and let me know if that's suitable for your request?

Thank you.

**Comment by vaibhavjayas** [comment]
i tried and it works but it has missing VM status like active stopped or running

**Comment by niedbalski** [comment]
@vaibhavjayas the metric value itself indicates the status. (check: https://github.com/openstack-exporter/openstack-exporter/blob/master/nova.go#L10)

**Comment by niedbalski** [comment]
@vaibhavjayas I've added the status field also + the metric value itself.
