### ISSUE TITLE
dial tcp: i/o timeout

### ISSUE THREAD

**Issue by rycaputo** [openstack-exporter/openstack-exporter#114]
ERRO[0030] enabling exporter for service <service> failed: dial tcp: i/o timeout  source="main.go:63"

I have tested my clouds.yaml everything seems to be working but I get i/o timeouts

**Comment by rycaputo** [comment]
-net=host in the docker command when this happens

**Comment by niedbalski** [comment]
@rycaputo do you have the full logs to take a look? also a escaped clouds.yaml would be helpful

**Comment by rycaputo** [comment]
I figured it out in the docket command to deploy I added -net=host to pass the host networks to the container
