### ISSUE TITLE
read /etc/openstack/clouds.yaml: is a directory ERROR

### ISSUE THREAD

**Issue by nshah011393** [openstack-exporter/openstack-exporter#118]
Hello!

I am using docker as the install method, but getting the below Go error: (repeats for the different services)

ERRO[0000] enabling exporter for service load-balancer failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:63"

The file is not a directory though. Is there something I might be missing or some permission?

Thank you!

**Comment by dthpulse** [comment]
how did you solve this? Have same issue here. thx
