### ISSUE TITLE
url lack of ip or hostname when get service

### ISSUE THREAD

**Issue by adgarr** [openstack-exporter/openstack-exporter#121]
team,
when I start to  runn openstack-exporter, echo error message: "error: failed to collect metric: images, error: Get http://:9292/v2/images: dial tcp :9292: connect: connection refused  source="exporter.go:128""

**Comment by adgarr** [comment]
clouds.yaml:
clouds:
 openstack01:
   region_name: RegionOne
   identity_api_version: 3
   identity_interface: internal
   auth:
     username: admin
     password: 123456
     project_name: admin
     project_domain_name: 'Default'
     user_domain_name: 'Default'
     auth_url: http://xxxxxx:5000/v3
   verify: false

start cmd:
./openstack-exporter --os-client-config ./clouds.yaml openstack01

**Comment by alexeymyltsev** [comment]
Do you have endpoint in keystone for images(glance)?
Could you check it with 
```openstack endpoint list | grep image```

**Comment by adgarr** [comment]
echo result:
  0a2c3b8a8e9644d8afd0a20e9d8621c5 | RegionOne | glance       | image          | True    | public    | http://:9292

then  i exec cmd with ''' --endpoint-type="internal" '''
now,it's ok. Thanks!
