### ISSUE TITLE
[bug] metric:openstack_neutron_up is not correct

### ISSUE THREAD

**Issue by adgarr** [openstack-exporter/openstack-exporter#122]
when I stop or run neutron_server, the openstack_neutron_up is always 0

**Comment by alexeymyltsev** [comment]
Could you check endpoints for neutron? 
Does this endpoint available?

**Comment by adgarr** [comment]
@alexeymyltsev it's ok. when I run cmd with ' --disable-metric=neutron-loadbalancers', i can get correct result. but when i run cmd with no  ' --disable-metric=neutron-loadbalancers', the result is error.  my oepnstack  turn off loadbalancer

**Comment by alexeymyltsev** [comment]
@adgarr you are right, I have same behaves on my stand.

**Comment by adgarr** [comment]
@alexeymyltsev maybe, the failure to collect loadbalancers due to this problem

**Comment by alexeymyltsev** [comment]
@adgarr As I see in Neutron there are metrics about loadalancers and [here](https://github.com/openstack-exporter/openstack-exporter/blob/0ebcb781767d5f6d0850ab286cf77c4e601d1a84/exporters/exporter.go#L120-L141) if collection one of metrics failed, "up" metric will be 0.

**Comment by niedbalski** [comment]
@alexeymyltsev @adgarr thank you for the report. I think assuming that up is 0 when any of the collections fails is plainly wrong. I'll change this behavior.

Thank you for reporting.
