### ISSUE TITLE
v0.0.9 image fails when starting

### ISSUE THREAD

**Issue by mikejoh** [openstack-exporter/openstack-exporter#13]
When starting the v0.0.9 image it fails with the following error:
```
Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/openstack-exporter\": stat /bin/openstack-exporter: no such file or directory": unknown
Error: failed to start containers: openstack_exporter
```
`WORKDIR` should've been `COPY` instead, looking at this line:
https://github.com/openstack-exporter/openstack-exporter/blob/8ccaaf52ac280a8d2c542be9a192ef90eb1ce26e/Dockerfile#L8

**Comment by niedbalski** [comment]
@mikejoh 

ouch!, thanks for spotting this issue. None of the building steps were running a test on top of the built image. This https://github.com/openstack-exporter/openstack-exporter/commit/6864fdd980c45abbd5156232ab53aed79b45b017 adds a check on the building process for assuring /bin/openstack-exporter is there and changes the workdir to copy as you mentioned.

Please pull :master or 0.0.9 tags and check yourself before I can close this bug.

Thanks!

**Comment by mikejoh** [comment]
@niedbalski 

Cool, thanks for fixing this with a short notice!

Confirmed working now when running `v0.0.9` and `master`. Closing issue!
