### ISSUE TITLE
Need advice about metrics collect time too long

### ISSUE THREAD

**Issue by Midori-ch** [openstack-exporter/openstack-exporter#132]
Hi ,
**What happened:**
* The metrics "limits_volume_max_gb" took a long time to collect.
   (As below, it around 10min)
![image](https://user-images.githubusercontent.com/11845196/95821526-ac12d600-0d5c-11eb-89f3-647136521de1.png)

* Try to disable this metrics on test environment but no luck.
```
[Service]
Type=simple
ExecStart=/opt/prometheus/openstack-exporter/openstack-exporter \
          --os-client-config=/opt/prometheus/openstack-exporter/clouds.yaml default --collect-metric-time \
          --disable-metric=openstack_nova-limits_vcpus_max \
          --disable-metric=openstack_cinder-limits_volume_max_gb
```
* Log：Still collected metrics for exporter
```
level=info msg="Collected metrics for exporter: openstack_nova, metric: limits_vcpus_max" source="exporter.go:113"
level=info msg="Collecting metrics for exporter: openstack_cinder, metric: limits_volume_max_gb" source="exporter.go:106"
```
* Is there a better way that I can reduce the collect time ?

**Comment by alexeymyltsev** [comment]
Hi @Midori-ch looks like you type incorrect metric name:
```
openstack_nova_limits_vcpus_max
openstack_cinder_limits_volume_max_gb
```
Anyway 11 min and 5 min are huge numbers.
Could you try to collect quote limits and usage with CLI and check time for collection?
For example:
```time cinder -d quota-usage <PROJECT_ID>```

**Comment by Midori-ch** [comment]
@alexeymyltsev 
* Thank you for your helping.  But I changing metrics and reload/restart service still receive those metrics. 
* And this is result of 
`time cinder -d quota-usage teamae`
```
+------------------------------+--------+----------+-------+-----------+
| Type                                             | In_use | Reserved | Limit | Allocated |
+------------------------------+--------+----------+-------+-----------+
| backup_temoes                    | 0      | 0        | 1000  |           |
| backups                                      | 0      | 0        | 10    |           |
| temoes                                   | 0      | 0        | -1    |           |
| temoes_sp-hdd               | 0      | 0        | -1    |           |
| temoes_sp-hdd-old       | 0      | 0        | -1    |           |
| temoes_sp-ssd                | 0      | 0        | -1    |           |
| temoes_hdd                          | 0      | 0        | -1    |           |
| temoes_hdd+                       | 0      | 0        | -1    |           |
| temoes_hdd-old                  | 0      | 0        | -1    |           |
| temoes_hdd-strict               | 0      | 0        | -1    |           |
| temoes_ssd                           | 0      | 0        | -1    |           |
| temoes_ssd-NonMultiattach | 0      | 0        | -1    |           |
| temoes_ssd-thick                 | 0      | 0        | -1    |           |
| groups                                        | 0      | 0        | 10    |           |
| per_volume_temoes            | 0      | 0        | -1    |           |
| snapshots                                  | 0      | 0        | -1    |           |
| snapshots_sp-hdd              | 0      | 0        | -1    |           |
| snapshots_sp-hdd-old       | 0      | 0        | -1    |           |
| snapshots_sp-ssd                | 0      | 0        | -1    |           |
| snapshots_hdd                          | 0      | 0        | -1    |           |
| snapshots_hdd+                       | 0      | 0        | -1    |           |
| snapshots_hdd-old                  | 0      | 0        | -1    |           |
| snapshots_hdd-strict               | 0      | 0        | -1    |           |
| snapshots_ssd                           | 0      | 0        | -1    |           |
| snapshots_ssd-NonMultiattach | 0      | 0        | -1    |           |
| snapshots_ssd-thick                     | 0      | 0        | -1    |           |
| volumes                                           | 0      | 0        | -1    |           |
| volumes_sp-hdd                       | 0      | 0        | -1    |           |
| volumes_sp-hdd-old               | 0      | 0        | -1    |           |
| volumes_sp-ssd                        | 0      | 0        | -1    |           |
| volumes_hdd                                  | 0      | 0        | -1    |           |
| volumes_hdd+                               | 0      | 0        | -1    |           |
| volumes_hdd-old                          | 0      | 0        | -1    |           |
| volumes_hdd-strict                       | 0      | 0        | -1    |           |
| volumes_ssd                                   | 0      | 0        | -1    |           |
| volumes_ssd-NonMultiattach    | 0      | 0        | -1    |           |
| volumes_ssd-thick                        | 0      | 0        | -1    |           |
+------------------------------+--------+----------+-------+-----------+

real    0m1.746s
user    0m0.678s
sys     0m0.115s
```

**Comment by Hybrid512** [comment]
I already mentionned huge delays with openstack exporter.
More than 10mn sometimes.
In my case, the problem was related to Heat creating dozens of domains for stacks and even if those stacks are deleted, those domains still exists, even though they are empty.
This add an extraordinary huge latency when because the exporter is scraping every objects from every domains and with hundreds of nearly empty domains, it takes a huge amount of time since  does at least an API call per domain and since the API itself is not that quick to answer, it's just useless.
I ended hacking the exporter to hardcode the domain we use until there is a better option and now, my scrape time went from >10mn to less than 10s.

More details here : https://github.com/openstack-exporter/openstack-exporter/issues/110

**Comment by alexeymyltsev** [comment]
Maybe you have huge numbers of projects as @Hybrid512 .
Could you check it with ```openstack project list  -f value | wc -l``` ?

**Comment by Midori-ch** [comment]
@alexeymyltsev
This environment have large number of projects, almost 3000.

**Comment by alexeymyltsev** [comment]
@Midori-ch interesting, all this projects are needed or most of them is garbage from something like tempest?

**Comment by Midori-ch** [comment]
@alexeymyltsev 
This problem may similar like @Hybrid512 he said. After check this environment, all of these projects was created by domain "heat_user_domain".  Just this one created 2600 projects.  Try to clarify these project is using or not.
Thank you @alexeymyltsev and @Hybrid512 for helping me.

**Comment by rudolfkastl** [comment]
openstack_metric_collect_seconds{openstack_metric="agent_state",openstack_service="openstack_cinder"} 0.614940848
openstack_metric_collect_seconds{openstack_metric="agent_state",openstack_service="openstack_neutron"} 0.281257217
openstack_metric_collect_seconds{openstack_metric="agent_state",openstack_service="openstack_nova"} 0.065427595
openstack_metric_collect_seconds{openstack_metric="availability_zones",openstack_service="openstack_nova"} 0.221963442
openstack_metric_collect_seconds{openstack_metric="domains",openstack_service="openstack_identity"} 0.111838646
openstack_metric_collect_seconds{openstack_metric="flavors",openstack_service="openstack_nova"} 0.049086739
openstack_metric_collect_seconds{openstack_metric="floating_ips",openstack_service="openstack_neutron"} 0.233218322
openstack_metric_collect_seconds{openstack_metric="groups",openstack_service="openstack_identity"} 0.087322546
openstack_metric_collect_seconds{openstack_metric="objects",openstack_service="openstack_object_store"} 0.62824971
openstack_metric_collect_seconds{openstack_metric="pool_capacity_free_gb",openstack_service="openstack_cinder"} 0.028077002
openstack_metric_collect_seconds{openstack_metric="regions",openstack_service="openstack_identity"} 0.155061645
openstack_metric_collect_seconds{openstack_metric="running_vms",openstack_service="openstack_nova"} 0.257535111
openstack_metric_collect_seconds{openstack_metric="snapshots",openstack_service="openstack_cinder"} 0.204933035
openstack_metric_collect_seconds{openstack_metric="network_ip_availabilities_total",openstack_service="openstack_neutron"} 1.354868205
openstack_metric_collect_seconds{openstack_metric="projects",openstack_service="openstack_identity"} 1.463273565
openstack_metric_collect_seconds{openstack_metric="security_groups",openstack_service="openstack_nova"} 1.140361678
openstack_metric_collect_seconds{openstack_metric="users",openstack_service="openstack_identity"} 2.161259503
openstack_metric_collect_seconds{openstack_metric="routers",openstack_service="openstack_neutron"} 4.199533992
openstack_metric_collect_seconds{openstack_metric="images",openstack_service="openstack_glance"} 6.026076676
openstack_metric_collect_seconds{openstack_metric="subnets",openstack_service="openstack_neutron"} 9.542604065
openstack_metric_collect_seconds{openstack_metric="networks",openstack_service="openstack_neutron"} 13.506773833
openstack_metric_collect_seconds{openstack_metric="security_groups",openstack_service="openstack_neutron"} 34.41325965
openstack_metric_collect_seconds{openstack_metric="port",openstack_service="openstack_neutron"} 71.092565625
openstack_metric_collect_seconds{openstack_metric="total_vms",openstack_service="openstack_nova"} 197.328686473
openstack_metric_collect_seconds{openstack_metric="limits_vcpus_max",openstack_service="openstack_nova"} 318.08911142
openstack_metric_collect_seconds{openstack_metric="volumes",openstack_service="openstack_cinder"} 449.505290008
openstack_metric_collect_seconds{openstack_metric="limits_volume_max_gb",openstack_service="openstack_cinder"} 2131.627758229

**Comment by alexeymyltsev** [comment]
@Midori-ch looks like I was wrong about naming for disabling metrics.
As you can see here: https://github.com/openstack-exporter/openstack-exporter/blob/a8ccd288ec8e9d629490c9c9d9b0683e547ec469/exporters/exporter.go#L77-L84 
function try to match ```exporter name```-```metric name```, exporter name is ```nova``` as you can see here:
https://github.com/openstack-exporter/openstack-exporter/blob/a8ccd288ec8e9d629490c9c9d9b0683e547ec469/exporters/nova.go#L82-L94
you should use for example ```nova-limits_vcpus_max```

**Comment by niedbalski** [comment]
@alexeymyltsev @Midori-ch @rudolfkastl @jocelynthode 

Hello All,

First thank you very much for your interest on this project and for all your proposals and great bug reports.
I would like to discuss with you some issues I think we need to tackle/fix part of the performance issues presented here
and see if anyone is up for a feature/PR.

1) Focus some optimizations on metrics that takes more than 10s to be gathered.

openstack_metric_collect_seconds{openstack_metric="networks",openstack_service="openstack_neutron"} 13.506773833
openstack_metric_collect_seconds{openstack_metric="security_groups",openstack_service="openstack_neutron"} 34.41325965
openstack_metric_collect_seconds{openstack_metric="port",openstack_service="openstack_neutron"} 71.092565625
openstack_metric_collect_seconds{openstack_metric="total_vms",openstack_service="openstack_nova"} 197.328686473
openstack_metric_collect_seconds{openstack_metric="limits_vcpus_max",openstack_service="openstack_nova"} 318.08911142
openstack_metric_collect_seconds{openstack_metric="volumes",openstack_service="openstack_cinder"} 449.505290008
openstack_metric_collect_seconds{openstack_metric="limits_volume_max_gb",openstack_service="openstack_cinder"} 2131.627758229

2) Provide a way to flag slow metrics and disable them entirely via command line (#134)  -- I implemented this
which by default is False.

3) Implement a project/domain or tenant filtering to be able to say `--include-project=x,y,z` or --exclude-project (heat, i.e.)

4) Implement end-to-end testing with memory/cpu profiling to avoid regressions 

Please feel free to work on any of the items or discuss here if any other idea can be beneficial for the overall exporter performance.

Thanks!

**Comment by alexeymyltsev** [comment]
@niedbalski Hello, I'm not sure if this flag is needed(https://github.com/openstack-exporter/openstack-exporter/pull/134) because metrics can be slow depends of environment. 
If some environment have a lot of routers, than another metrics will be slow. 
We can't predict all cases. 
From my point of view we should provide flexibility for disabling metrics, limitation of projects and domains. 
Administrator of environment should decide by himself how and what he will be collect.

**Comment by rudolfkastl** [comment]
What i dont understand is that simply downloading the page with curl takes
so long. Can we simply decouple the metrics gathering and the html page?

**Comment by alexeymyltsev** [comment]
It is possible, I did it in own openstack-exporter. With this approach needed add gathering timer to config(we can't increase granularity with scrape interval) and add mutex to metrics. Without mutex exporter will create a lot of goroutines.
All fast metrics will be refreshed with tick of timer, but slow metrics will be refreshed as rare.

**Comment by alexeymyltsev** [comment]
@niedbalski what do you think about everything above?

**Comment by Midori-ch** [comment]
> you should use for example `nova-limits_vcpus_max`
Thank you @alexeymyltsev. 
@niedbalski 
Just a primitive opinion. After exclude those projects are not using, exporter working smoothly. 
If there a config for user can determine domain for metrics gathering that would be helpful.

**Comment by niedbalski** [comment]
@Midori-ch I've included the --disable-slow-metrics=true that will disable some of the limits-* metrics , by default is turned off but we at least have a way to discard metrics that we know beforehand are resource exhaustive.
