### ISSUE TITLE
Request for metrics forbidden code:403

### ISSUE THREAD

**Issue by c-android** [openstack-exporter/openstack-exporter#136]
I'm using docker to run the exporter.  A few  metrics are being exported but detailed information is missing. When I run with --log.level debug, I see a lot of 403 errors

`docker run -p 9180:9180 -v /etc/openstack/clouds.yaml:/etc/openstack/clouds.yaml -it quay.io/niedbalski/openstack-exporter-linux-amd64:master devstack --log.level debug`

`ERRO[0010] Failed to collect metric for exporter: identity, error: failed to collect metric: users, error: Request forbidden: [GET http://<host_up>/identity/v3/users], error message: {"error":{"code":403,"message":"You are not authorized to perform the requested action: identity:list_users.","title":"Forbidden"}}  source="exporter.go:130" ` 
`ERRO[0010] Failed to collect metric for exporter: identity, error: failed to collect metric: groups, error: Request forbidden: [GET http://<host_ip>/identity/v3/groups], error message: {"error":{"code":403,"message":"You are not authorized to perform the requested action: identity:list_groups.","title":"Forbidden"}}  source="exporter.go:130"

etc...

UPDATE:

Evidently in my devstack deployment an auth token must be sent with API calls.   A simple command line example

`curl http://<host_ip>/identity/v3/users`
`{"error":{"code":401,"message":"The request you have made requires authentication.","title":"Unauthorized"}}`

When I create a token and send it with the request, I get the expected response

`curl http://<host_ip>/identity/v3/users  -H "X-Auth-Token: "$TOKEN""`
{{ list of users }}

Request:  Support passing an X-Auth-Token with API requests

**Comment by niedbalski** [comment]
Dear @c-android 

Passing a auth-token is possible through the 'token' entry in the auth section of the clouds.yaml (check https://github.com/gophercloud/utils/blob/3b35bcb43167f6d8080fa824c480f04b60311b51/openstack/clientconfig/results.go#L53 )

Please let me know if that solves the issue for you.

**Comment by niedbalski** [comment]
Since no more feedback has been received on this bug from @c-android , I am closing it.
