### ISSUE TITLE
Add metrics for project quota

### ISSUE THREAD

**Issue by mytxyang-arm** [openstack-exporter/openstack-exporter#137]
Sometime we need check if the cpu/memory/volume usage is break through the quota limit, so query the project quota is necessary, could you please add a feature to query the project quota?

**Comment by alexeymyltsev** [comment]
Hello @mytxyang-arm. 
Looks like those are metrics that you are looking for:
```
openstack_nova_limits_vcpus_max
openstack_nova_limits_vcpus_used
openstack_nova_limits_memory_max
openstack_nova_limits_memory_used
openstack_cinder_limits_volume_max_gb
openstack_cinder_limits_volume_used_gb
```

**Comment by niedbalski** [comment]
@alexeymyltsev appreciated, yes. I agree those are the metrics you're looking for.
