### ISSUE TITLE
New metrics for nova

### ISSUE THREAD

**Issue by robinlem** [openstack-exporter/openstack-exporter#142]
Hi !
In your exporter we have the metrics : openstack_nova_local_storage_used_bytes based on local_gb_used nova's hypervisor proprerty
Very nice. But can you add the property free_disk_gb ? this is interesting for those who do thin provisioning and want to know how much disk is left.

Regards and thank you

**Comment by alexeymyltsev** [comment]
Hi @robinlem,
Do you have any idea from which API call we can collect free_disk_gb info?
For collection this information in our cluster we use node-exporter.

**Comment by robinlem** [comment]
Hi thanks for your response. 

I don't realy now which API you can use.
The info come from : $ openstack hypervisor stats show
using node exporter is a bit complicated because we do not know on which partition the qcow files are located. Free disk from nova should be much more relevant.

Thanks

**Comment by alexeymyltsev** [comment]
@robinlem unfortunately we do not use thin provisioning. Can you confirm what ```free_disk_gb``` show real free size of disk which used for ephemeral disks?
If it is real size of free space I can add this metric to exporter.

**Comment by robinlem** [comment]
Yes you're right. 
free_disk_gb show real free size (and real "final" free disk even if you are in thin).
If you can add that it's awesome 
Regards

**Comment by niedbalski** [comment]
Fixed on #145
