### ISSUE TITLE
[Feature Request] Allow subset of projects to be selected to enable sharding / partitioning of metric scraping

### ISSUE THREAD

**Issue by frittentheke** [openstack-exporter/openstack-exporter#146]
The exporter potentially fetches an ever greater number of metrics. Certainly doing things in parallel will get you much further, but with larger installations at some point one inevitably runs into scaling issues trying to fetch ALL of the metrics of all domains and projects in a single scrape or with a single exporter instance ...

This feature idea is of similar motivation as request #110, which suggests to add a domain filter to, due to very long running scrapes when doing them all, only fetch metrics for projects in a particular domain. While certainly a valid use case - only being interested in one particular domain this does not particularly help in scaling the metrics export.

Considering a scrape interval of 5, 15 or even 30 minutes this means a single OpenStack-Exporter instance is doing nothing for most of the time and then a giant burst of metrics are collected and returned to Prometheus.

But Prometheus on the other hand is designed and very capable of scraping A LOT of individual targets. To do this efficiently will attempt to evenly distribute the scrape of different targets over the scraping interval - https://github.com/prometheus/prometheus/blob/release-2.23/scrape/target.go#L154

unfortunately this does only work when there are multiple targets.

I therefore suggest to introduce some sort of parition or sharding key to be sent with the GET request as url parameter and to allow an openstack-exporter instance to be queried for only a subset of the projects. 

I explicitly suggest to allow this to happen dynamically and not via a static configuration parameter as this would allow a flexible design to either:

* Run multiple exporters, each responsible for a subset of domains/projects, them again being distributed over the scrape interval and potentially hitting different API endpoints / databases or even being scraped by different Prometheus servers

* Or use a single exporter, but apply the multi-target pattern (https://prometheus.io/docs/guides/multi-target-exporter/#the-multi-target-exporter-pattern),usually used by blackbox exporters, to iterate over the different project subsets. But now much more evenly distributed over the scrape interval

My idea somewhat follows the approach of hashed directories (i.e with Dovecot https://doc.dovecot.org/configuration_manual/mail_location/#directory-hashing). 
But since each project in OpenStack already has a UUID-based `id` field (https://docs.openstack.org/api-ref/identity/v3/?expanded=list-projects-detail) which is evenly distributed this could simply be used to select subsets.

i.e. `http://localhost:9180/metrics?project_id_prefix=a` would result in all projects which `id` starts with an `a` (https://golang.org/pkg/strings/#HasPrefix) to have their metrics fetched and returned. Or going with a regex approach to allow ranges `http://localhost:9180/metrics?project_id_regex=^[a-f]`.

If you somewhat like the idea - would you accept a PR for it?

**Comment by niedbalski** [comment]
@frittentheke thank you for taking the time to contribute and open a very interesting discussion here.

At first, you might want to know that I am not personally attached to the approach we're using right now
for scrapping and I understand that the project could surely benefit  from the multi-target pattern, in fact, you would be pleased to know that we are in the process to review/merge a proposal that goes on this line #141 as a first step, this would split the different clouds per probe and allow to parametrize the enabled/disabled services as well.

Considering your proposal I think it would be beneficial to have a filter per project_id that could help to solve #110, but be aware that this implies cascading the project-id to all metrics across all the services, so in a way this is a non-trivial change.

I would definitively accept a PR that follows this approach, please check #141 and consider parametrizing the project_id=X and project_id_regex=Z as part of the probe parameters that we're about to land.

**Comment by frittentheke** [comment]
@niedbalski thanks for this great feedback! :smile: 

Thank you especially for the reference to PR #141, which, apart from multi-cloud, already starts to introduce configuration per url parameters. I suppose I should likely base my PR with even more parameters on that one then?

**Comment by niedbalski** [comment]
@frittentheke well, if that's not opposed to your proposal, I think your work should be a place to start with (appending new parameters to partition/split by project uuid, etc on top of the existing ones on that PR). What are your thoughts on it? 

@alexeymyltsev any comments on this proposal before @frittentheke works on a this?

**Comment by alexeymyltsev** [comment]
@niedbalski thanks for involving me to this discussion.
 I have several question: 
- How this approach will provide generic metrics, for example vm per hypervisor? 
- Exporter collect information for most of metrics for all projects with one API call. If we will request all metrics per projects it can increase load on API. Do you take it into account?

**Comment by frittentheke** [comment]
@alexeymyltsev you brought up some very valid points.


I apologize for the wall of text in advance ...



1) As for the generic, non-project-related metrics I don't know if always fetching and returning those would be best.
Or even splitting the metrics of each service in a way that allows selecting "global" or "per project" metrics, i.e. via url parameters like:  `include_services=network_global, network_perproject"`, is possible. But this would greatly over-engineer things a bit though.



2) As for API usage efficiency I might not have dug deep enough into the API spec before proposing my idea of solving scraping metrics off of huge clouds. 


a) The new capability to select only certain services via url parameter, introduced with #141, already allows to apply the multi-target pattern of Prometheus and drastically reduce the number of metrics fetched at once and also allows for a flexible architecture combining even multiple OpenStack exporters and Prometheus instances.


b) As for OpenStack API features required to pursue my suggested approach, there apparently is support to do pagination of results (see
https://specs.openstack.org/openstack/api-wg/guidelines/pagination_filter_sort.html) and this is also available via the Gophercloud Golang client, see: https://github.com/gophercloud/gophercloud/tree/master/pagination

This functionality could be applied internally in the exporter (instead of always doing `allPages()` ) to avoid producing insanely large responses. **Maybe using paging internally would let the exporter / API scale a little further.**


c) But there is much more than just returning the results in chunks / pages:
* limit/markers
* filtering

Just like the pagination, the support for limit and marker would also allow to query a subset of items and to fetch items in sizable chunks.
It likely makes not sense to have Prometheus or any client of the Openstack-Exporter having to control those values manually. But if there way a strictly monotonic number (contrary to project_id being a UUID),
this could be used to allow clients to request a limited number projects and their resources per scrape and then ask for the next block in another scrape - so the Openstack-Exporter would be providing some sort of paging then. Again this might be only built on a side effect of a certain field being usable for this.

**In any case using this feature to set an upper limit of items to request from a cloud is a good idea to not let the exporter kill the API or itself. Potentially indicating "truncated" data to the scraping client via some exporter state metric.**



d) Finally the filters (accessible via `listOpts`) apparently allow to filter on arbitrary and even resource specific fields and even seem to allow LIKE (regex) queries, numeric comparisons or multi-values.
Check out filtering only IPv4 subnets (https://github.com/gophercloud/gophercloud/blob/841705fad1df2f50b23c31ee60f51702063be7c6/openstack/networking/v2/subnets/doc.go#L14)





Maybe the key to solve many cases for tailoring the exporters work is to simply expose (most of) the OpenStack API filtering capabilities via the exporters url paramters. This would cover cases like #110, but also many others which are about selecting only certain metrics. Since you already have `include_services`, why not add url parameters like `filter_global` (to apply to ALL services) or `filter_$servicename` to only apply to this service and let our clients (Prometheus) select the particular resources they want their metrics for. This would then make the OpenStack-Exporter even more of a flexible Prometheus -> OpenStack API adapter.

And last but not least, even "my issue" of only fetching a subset of project_ids via some regex could be done this way without making this a special case for the exporter.

**Comment by alexeymyltsev** [comment]
@frittentheke sorry in advance if I misunderstood something.

Let's start from problem.
Large clouds would like to split metrics between targets and best solution would be use /probe with query. 

With https://github.com/openstack-exporter/openstack-exporter/pull/141 already there is possibility split service metrics between targets.

**Comment by alexeymyltsev** [comment]
@frittentheke sorry in advance if I misunderstood something.

Let's start from problem.
Large clouds would like to split metrics between targets and best solution would be use /probe with query. 

With https://github.com/openstack-exporter/openstack-exporter/pull/141 already there is possibility split service metrics between targets.

Ok that not enough and we would like to split metrics for projects.

### Filtering
As I see most of OpenStack API endpoint does not support regexp for project filterin. Only all_projects or one project. For example volume list [endpoint](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=list-accessible-volumes-with-details-detail#id95) .
It means that we can do separate request for each project(huge load for OpenStack API) or request all projects but filter items on exporter side. 
For me best is last one.

### General metrics
From my point of view with adding projects filtering we should filtering only metrics like volume_status, server_status or quota metrics and provide not filtered cumulative metrics like volumes, total_vms or ports. 
Looks like general metrics would be collected from each target. 

Additionally we should take account that big count of targets generate load on OpenStack API.

Just in case, if we would like collect a lot of data from OpenStack best solution is collecting it from DB(in one of public cloud collect their metrics in this way).

**Comment by niedbalski** [comment]
@alexeymyltsev @frittentheke 
Hello,

Thank you for bringing this interesting discussion, I'd like to add a few observations in order to decide whether or not we should embark ourselves into this feature request.

If the overall idea of this proposal is performance and the correct usage of the probe/multi target pattern,
it doesn't help much on this purpose to do openstack client side (exporter) filtering of the resulting objects that have been already fetched from the API. This still requires special project access and it is something that the final visualization tool or client can do using promQL with the generic metrics.

As @alexeymyltsev already pointed out, not all the endpoints we are using supports multiple project filtering, it is
per project or all_projects in most of the endpoints.

Although, I am keen to keep extending the probe's filtering infrastructure and I think that a project_id filter (single project) would
be useful for users that can benefit from to reduce load and scope of the probes by being able to scrape more particular targets.

Based on that, I'd like to suggest implementing:

1) Extend the current filtering code to allow custom query string parameters 
2) Extend the current filtering code to allow validators
3) Implement a pilot project_id that will cascade through the metrics to filter by project_id

Once we have this landed, we can continue to think on how we can benefit from a middleware or an extensible object
filter to allow client side filtering of the resulting objects.

I really appreciate any thoughts on this or further ideas.

**Comment by niedbalski** [comment]
@frittentheke hello, are you still interested to work on this item?

**Comment by niedbalski** [comment]
No work has been performed for the last month(s). Closing until someone else is interested to work on this.
