### ISSUE TITLE
Metrics for Loadbalancer

### ISSUE THREAD

**Issue by alexeymyltsev** [openstack-exporter/openstack-exporter#148]
No information about those metrics in README.

Some metrics  provide same things
One of it should be removed.

```
ch <- prometheus.MustNewConstMetric(exporter.Metrics["total_loadbalancers"].Metric,
	prometheus.GaugeValue, float64(len(allLoadbalancers)))
ch <- prometheus.MustNewConstMetric(exporter.Metrics["loadbalancers"].Metric,
	prometheus.GaugeValue, float64(len(allLoadbalancers)))
```

**Comment by niedbalski** [comment]
@alexeymyltsev hello!, thanks for noticing this issue, is this something you will follow up with a PR? I think we should remove loadbalances and document it as total_loadbalancers to match other metrics prefix.
