### ISSUE TITLE
issue when use --multi-cloud

### ISSUE THREAD

**Issue by shaotingEri** [openstack-exporter/openstack-exporter#162]
Hi,
When I try to use this option --multi-cloud together with --disable-service.object-store, seems --disable-service.object-store doesn't work.

I try to run opnstack like this: 
 ./openstack-exporter --os-client-config=/xxxx/clouds.yaml --disable-service.object-store --multi-cloud

and try to fetch the data: 
  curl "http://localhost:9180/probe?cloud=cloudxxx"

But it will spend almost 2 min to get the data.
And there is the information like below in the outputs.
     # HELP openstack_object_store_up up
     # TYPE openstack_object_store_up gauge
     openstack_object_store_up 1

So, I think the option --disable-service.object-store doesn't work when use together with --multi-cloud.
Can you help to have a look?

**Comment by levesduzw** [comment]
I can also confirm that `--disable-service` parameters didn't work for me with `--multi-cloud` (I've tried nova).
I understand this probe mode is pretty new. If client-side only filtering is a design choice, please make it more clear in the readme.

Interestingly, `--disable-metric` params still seem to work on the Exporter side.

**Comment by alexeymyltsev** [comment]
Hi, 
As far as I understood ```--disable-service``` does not works with ```--multi-cloud``` because there is ```exclude_services``` [like here](https://github.com/openstack-exporter/openstack-exporter#scrape-options). 
Do you think that it will be useful filter services with flags on exporter side? 
@niedbalski what do you think about it?

**Comment by shaotingEri** [comment]
For me, I think yes.
As it is supported by legacy mode.

**Comment by alexeymyltsev** [comment]
PR fix this issue
