### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by 3vaLpwner** [openstack-exporter/openstack-exporter#165]
Hello!
Seems like i've found a little bug or something. I've installed openstack_exporter, open http://IP:9180, press on Metrics, it grabs some metrics and fails after some time:
```
19:42:51 openstack-exporter[26370]: time="2021-03-15T19:42:51+03:00" level=info msg="Collected metrics for exporter: openstack_neutron, metric: network_ip_availabilities
19:42:51 openstack-exporter[26370]: time="2021-03-15T19:42:51+03:00" level=info msg="Collected metrics for exporter: openstack_nova, metric: total_vms" source="exporter.
19:42:54 openstack-exporter[26370]: panic: runtime error: invalid memory address or nil pointer dereference
19:42:54 openstack-exporter[26370]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d50e6]
19:42:54 openstack-exporter[26370]: goroutine 58 [running]:
19:42:54 openstack-exporter[26370]: github.com/openstack-exporter/openstack-exporter/exporters.ListVolumes(0xc0003b5140, 0xc0003b5260, 0xf02c20, 0x2)
19:42:54 openstack-exporter[26370]:         /app/exporters/cinder.go:110 +0xca6
19:42:54 openstack-exporter[26370]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).RunCollection(0xc0003b5140, 0xc0001eb310, 0xa505c
19:42:54 openstack-exporter[26370]:         /app/exporters/exporter.go:96 +0x20c
19:42:54 openstack-exporter[26370]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).Collect(0xc0003b5140, 0xc0003b5260)
19:42:54 openstack-exporter[26370]:         /app/exporters/exporter.go:117 +0x101
19:42:54 openstack-exporter[26370]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
19:42:54 openstack-exporter[26370]:         /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x19d
19:42:54 openstack-exporter[26370]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
19:42:54 openstack-exporter[26370]:         /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xe12
19:42:54 systemd[1]: openstack-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
19:42:54 systemd[1]: openstack-exporter.service: Failed with result 'exit-code'.
```
So can't load metrics.
Command line 
`usr/local/bin/openstack-exporter --os-client-config=/etc/exportercfg/openstack.yaml --disable-slow-metrics default`

**Comment by alexeymyltsev** [comment]
Hello @3vaLpwner. Could you show response of this [request](https://docs.openstack.org/api-ref/block-storage/v3/index.html?expanded=list-accessible-volumes-with-details-detail#list-accessible-volumes-with-details)?
Looks like in response there is not array with information about attachments.

**Comment by 3vaLpwner** [comment]
I am not so good in openstack administration, so please tell me what should i do to make this request?
Many thanks

**Comment by alexeymyltsev** [comment]
You can use curl for issue token, like this: 
`
curl -i \
  -H "Content-Type: application/json" \
  -d '
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "admin",
          "domain": { "id": "default" },
          "password": "PASSWORD"
        }
      }
    },
    "scope": {
        "project": {
            "domain": {
                "id": "default"
            },
            "name": "admin"
        }
    }
  }
}' \
  "https://<KEYSTONE_URL>:5000/v3/auth/tokens"
`
Please change keystone url, domain, project, username and password for your environment. 

In response find `x-subject-token:` and copy this string and use for below request:
`
curl -s  -H "X-Auth-Token: <TOKEN>"  https://<CINDER_URL>:8776/v3/<PROJECT_ID>/volumes/detail\?all_tenants\=true
`
Please replace CINDER_URL with endpoint of cinder

**Comment by niedbalski** [comment]
Hey @alexeymyltsev seems that this line https://github.com/openstack-exporter/openstack-exporter/commit/de1b6c26d42cc8e34e9e7b56ac03ecc61cc8acb0#diff-9e437cfda5b40a23adbafd857267fdf46bf34d1f53c0a69304980721b80bf42fR110

introduced a possible error, since attachments isn't guaranteed to exists in older API(s), could you
please add a volume.Attachments != nil && ...

**Comment by alexeymyltsev** [comment]
@niedbalski I thought about it and I did tests with fixtures without attachments sections and I didn't have a panic.
But anyway this additional test will be useful.

**Comment by niedbalski** [comment]
@alexeymyltsev check pr #167

**Comment by niedbalski** [comment]
@alexeymyltsev @3vaLpwner hello guys, could you please check that the latest docker image fixes the issue?

thanks!

**Comment by 3vaLpwner** [comment]
> 
> 
> You can use curl for issue token, like this:
> `curl -i \ -H "Content-Type: application/json" \ -d ' { "auth": { "identity": { "methods": ["password"], "password": { "user": { "name": "admin", "domain": { "id": "default" }, "password": "PASSWORD" } } }, "scope": { "project": { "domain": { "id": "default" }, "name": "admin" } } } }' \ "https://<KEYSTONE_URL>:5000/v3/auth/tokens"`
> Please change keystone url, domain, project, username and password for your environment.
> 
> In response find `x-subject-token:` and copy this string and use for below request:
> `curl -s -H "X-Auth-Token: <TOKEN>" https://<CINDER_URL>:8776/v3/<PROJECT_ID>/volumes/detail\?all_tenants\=true`
> Please replace CINDER_URL with endpoint of cinder

Pretty much to replace in curl request. Please highlight where i should to replace username, password and domain name?
Thanks a lot!

**Comment by alexeymyltsev** [comment]
I hope so this will be more readable.
```
curl -i \
  -H "Content-Type: application/json" \
  -d '
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "<USERNAME>",
          "domain": { "id": "<DOMAIN_ID OF USER>" },
          "password": "<PASSWORD>"
        }
      }
    },
    "scope": {
        "project": {
            "domain": {
                "id": "<DOMAIN_ID OF PROJECT"
            },
            "name": "<PROJECT NAME>"
        }
    }
  }
}' \
  "https://<KEYSTONE_URL>:5000/v3/auth/tokens"
```

**Comment by 3vaLpwner** [comment]
Yeah, it works! I made first request, and it shows some info (attached).
Then i've put token and cinder_url in second request and it drops on screen a lot of info about volumes (can't even figure out how to organize that info)
Anyway, i have more than 40 projects, i should to check all of them by this way till i find bad empty one?
![изображение](https://user-images.githubusercontent.com/80704041/111355540-833e9600-8698-11eb-9635-de66a72af505.png)

**Comment by alexeymyltsev** [comment]
> Yeah, it works! I made first request, and it shows some info (attached).
> Then i've put token and cinder_url in second request and it drops on screen a lot of info about volumes (can't even figure out how to organize that info)
You can use VSCode or something like this which can do pretty JSON.
> Anyway, i have more than 40 projects, should i to check all of them by this way till i find bad request or empty one?
Volume list already have parameter `all_tenants'. 
If you do not have some sensitive data in this output you can share it with https://pastebin.com or sent me directly. 
> ![изображение](https://user-images.githubusercontent.com/80704041/111355540-833e9600-8698-11eb-9635-de66a72af505.png)

**Comment by 3vaLpwner** [comment]
This one:
[all-info.txt](https://github.com/openstack-exporter/openstack-exporter/files/6151406/all-info.txt)

**Comment by alexeymyltsev** [comment]
I ran tests with your output as fixtures and I didn't have any panic.
Anyway could you check the latest docker image?

**Comment by 3vaLpwner** [comment]
Sorry, can't test it with docker.

**Comment by alexeymyltsev** [comment]
you can build from master.

**Comment by 3vaLpwner** [comment]
Well, i did nothing, restarted daemon and everything is going OK. Not sure if it was something on my side, but we will see in a longterm. Closing this issue for now. Thanks to everyone!
