### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by Alexvianet** [openstack-exporter/openstack-exporter#17]
Do u have any default grafana dashboard like https://grafana.com/grafana/dashboards/7924
for openstack-exporter metrics ?

**Comment by Alexvianet** [comment]
If yes please provide url to README, thanks

**Comment by niedbalski** [comment]
@Alexvianet I had a preliminary dashboard https://grafana.com/grafana/dashboards/9701 , but it would be very nice if you can help us by extending / updating it with new metrics and graphs.

**Comment by niedbalski** [comment]
Hello @Alexvianet , Is this something of your interest that you would like to work on? I am happy to create a secondary repository under the openstack-exporter organization for the grafana dashboard, so we can contribute (and make you maintainer there).

**Comment by Alexvianet** [comment]
I am not.
No time for it, https://grafana.com/grafana/dashboards/9701 works for me now
