### ISSUE TITLE
Issue with service_up values

### ISSUE THREAD

**Issue by brfpm** [openstack-exporter/openstack-exporter#173]
Hi,

When I stop a service (cinder,glance,etc..) their service_up is always 1. 
Service_up is 0 when all metrics fail but when a metric doesn't have a function handler the metricsDown variable is not incremented. If a service has one metric without a function handler, service_up will never be 0.
 
I'm missing something? Is this on purpose or a bug?

**Comment by alexeymyltsev** [comment]
Hi @brfpm , thank you, this is bug I will work on it.
