### ISSUE TITLE
HTTP 500 Error

### ISSUE THREAD

**Issue by emarins** [openstack-exporter/openstack-exporter#176]
Hello,

I was able to install openstack-exporter in my container environment.  However, I am getting the following error trying to start the service.
-------
An error has occurred while serving metrics:
 
14 error(s) occurred:
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"92635516-c9ee-4c19-be87-a9dba139c8f0" > label:<name:"name" value:"ks_san_tst" > label:<name:"tenant_id" value:"1d8ad78ca7cd40c7a4beeeee3fe6cf71" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"bd237227-ae64-42d7-967b-81beb98beff6" > label:<name:"name" value:"kstest" > label:<name:"tenant_id" value:"1d8ad78ca7cd40c7a4beeeee3fe6cf71" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"beb3905b-f029-4d47-9b55-e0f050c3b4b3" > label:<name:"name" value:"grafana-test" > label:<name:"tenant_id" value:"1d8ad78ca7cd40c7a4beeeee3fe6cf71" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"09a0c811-a252-459a-9444-afe2d937710f" > label:<name:"name" value:"server1682-dev" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"103081b7-66f4-4c62-9c19-0b8586b217c0" > label:<name:"name" value:"server1723-dev" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"3ef2d4e5-2893-4f28-91b3-54790ecd5d0c" > label:<name:"name" value:"server1736-dev" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"46d2429e-4341-4437-bc53-5321dc70be14" > label:<name:"name" value:"server1685-dev" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"4ba940c8-9f2d-4160-a07a-9a4123895237" > label:<name:"name" value:"server1864-dev" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"5cc3311e-c2f1-4958-aa08-2e198f00e914" > label:<name:"name" value:"rhel83ks" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"63010b2c-2e97-44b9-9f52-f45c53679d14" > label:<name:"name" value:"server1838-dev" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"aa3d8f78-d3cb-44cd-9bc8-3205277f36c2" > label:<name:"name" value:"server2020-dev" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"fc92fba3-b5b4-46b1-b4f1-ebf5e7a68b97" > label:<name:"name" value:"server1879-dev" > label:<name:"tenant_id" value:"39a2a73b8c6740f5982ce2d237f912ac" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"239a42f7-7789-42b3-a528-8b7ae2893aa5" > label:<name:"name" value:"idrsareturn" > label:<name:"tenant_id" value:"fcbc20faa9504cfe80f2b90468261cef" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_nova_server_local_gb" { label:<name:"id" value:"748b6d34-3b3b-4dee-9cbd-23b71a08bb69" > label:<name:"name" value:"rhel82" > label:<name:"tenant_id" value:"fcbc20faa9504cfe80f2b90468261cef" > gauge:<value:0 > } was collected before with the same name and label values

If I use --disable-service.compute option to start openstack-exporter,   the service starts without problem.  Is it a bug?  Any tip to solve this problem ?

Thank you

**Comment by alexeymyltsev** [comment]
Hello @emarins,
Is this errors from openstack-exporter or from prometheus? 
It is quite strange because we collect this metrics with below loop and we should not have duplicates.
```
// Server status metrics
  for _, tenant := range allTenantsUsage {
	for _, server := range tenant.ServerUsages {
		ch <- prometheus.MustNewConstMetric(exporter.Metrics["server_local_gb"].Metric,
			prometheus.GaugeValue, float64(server.LocalGB), server.Name, server.InstanceID, tenant.TenantID)
	}
}
```

**Comment by alexeymyltsev** [comment]
You do not have this error with 1.3.0 because this versions does not have metric ```server_local_gb```.

Could you provide output for request usage for tenant: 39a2a73b8c6740f5982ce2d237f912ac  ?
https://docs.openstack.org/api-ref/compute/?expanded=show-server-diagnostics-detail,show-usage-statistics-for-tenant-detail#show-usage-statistics-for-tenant

With this output I can test code locally.

**Comment by emarins** [comment]
Hello @alexeymyltsev ,

Here is the output of the statistics command.

# curl -g -i --cacert "/etc/pki/tls/certs/icic.crt" -X GET https://x.x.x.x:8774/v2.1/os-simple-tenant-usage/39a2a73b8c6740f5982ce2d237f912ac -H "Accept: application/json" -H "OpenStack-API-Version: compute 2.72" -H "User-Agent: python-novaclient" -H "X-Auth-Token: ${OS_TOKEN}" -H "X-OpenStack-Nova-API-Version: 2.72"
HTTP/2 200 
date: Thu, 01 Apr 2021 09:02:35 GMT
server: Apache
x-content-type-options: nosniff
strict-transport-security: max-age=31536000; includeSubdomains; preload
content-length: 6400
content-type: application/json
openstack-api-version: compute 2.72
x-openstack-nova-api-version: 2.72
vary: OpenStack-API-Version,Accept-Encoding,User-Agent,X-OpenStack-Nova-API-Version
x-openstack-request-id: req-0bb182c7-13d6-4ee9-a7ad-1361e7ff7d33
x-compute-request-id: req-0bb182c7-13d6-4ee9-a7ad-1361e7ff7d33

{"tenant_usage": {"tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "server_usages": [{"hours": 1.111111111111111e-09, "flavor": "c2.m4", "instance_id": "09a0c811-a252-459a-9444-afe2d937710f", "name": "g41zr00001682-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 2, "started_at": "2021-02-19T16:49:58.000000", "ended_at": null, "state": "active", "uptime": 3514357}, {"hours": 1.111111111111111e-09, "flavor": "c1.m16", "instance_id": "103081b7-66f4-4c62-9c19-0b8586b217c0", "name": "g41zr00001723-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 16384, "local_gb": 0, "vcpus": 1, "started_at": "2021-02-25T14:59:55.000000", "ended_at": null, "state": "active", "uptime": 3002560}, {"hours": 1.111111111111111e-09, "flavor": "c1.m4", "instance_id": "3ef2d4e5-2893-4f28-91b3-54790ecd5d0c", "name": "g41zr00001736-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2021-03-01T20:35:47.000000", "ended_at": null, "state": "active", "uptime": 2636808}, {"hours": 1.111111111111111e-09, "flavor": "c1.m4", "instance_id": "46d2429e-4341-4437-bc53-5321dc70be14", "name": "g41zr00001685-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2021-02-19T20:42:17.000000", "ended_at": null, "state": "stopped", "uptime": 3500418}, {"hours": 1.111111111111111e-09, "flavor": "c2.m16", "instance_id": "4ba940c8-9f2d-4160-a07a-9a4123895237", "name": "g41zr00001864-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 16384, "local_gb": 0, "vcpus": 2, "started_at": "2021-03-22T15:30:26.000000", "ended_at": null, "state": "active", "uptime": 840729}, {"hours": 1.111111111111111e-09, "flavor": "36bafb7617af2c5cc4b7f64fb251dede", "instance_id": "5cc3311e-c2f1-4958-aa08-2e198f00e914", "name": "rhel83ks", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2021-03-18T15:07:44.000000", "ended_at": null, "state": "active", "uptime": 1187691}, {"hours": 1.111111111111111e-09, "flavor": "c1.m4", "instance_id": "63010b2c-2e97-44b9-9f52-f45c53679d14", "name": "g41zr00001838-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2021-03-18T17:22:45.000000", "ended_at": null, "state": "active", "uptime": 1179590}, {"hours": 1.111111111111111e-09, "flavor": "36bafb7617af2c5cc4b7f64fb251dede", "instance_id": "aa3d8f78-d3cb-44cd-9bc8-3205277f36c2", "name": "g41zr00002020-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2020-12-14T22:26:19.000000", "ended_at": null, "state": "active", "uptime": 9282976}, {"hours": 1.111111111111111e-09, "flavor": "c1.m16", "instance_id": "fc92fba3-b5b4-46b1-b4f1-ebf5e7a68b97", "name": "g41zr00001879-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 16384, "local_gb": 0, "vcpus": 1, "started_at": "2021-03-25T22:05:16.000000", "ended_at": null, "state": "active", "uptime": 557839}, {"hours": 1.111111111111111e-09, "flavor": "c2.m4", "instance_id": "09a0c811-a252-459a-9444-afe2d937710f", "name": "g41zr00001682-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 2, "started_at": "2021-02-19T16:49:58.000000", "ended_at": null, "state": "active", "uptime": 3514357}, {"hours": 1.111111111111111e-09, "flavor": "c1.m16", "instance_id": "103081b7-66f4-4c62-9c19-0b8586b217c0", "name": "g41zr00001723-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 16384, "local_gb": 0, "vcpus": 1, "started_at": "2021-02-25T14:59:55.000000", "ended_at": null, "state": "active", "uptime": 3002560}, {"hours": 1.111111111111111e-09, "flavor": "c1.m4", "instance_id": "3ef2d4e5-2893-4f28-91b3-54790ecd5d0c", "name": "g41zr00001736-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2021-03-01T20:35:47.000000", "ended_at": null, "state": "active", "uptime": 2636808}, {"hours": 1.111111111111111e-09, "flavor": "c1.m4", "instance_id": "46d2429e-4341-4437-bc53-5321dc70be14", "name": "g41zr00001685-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2021-02-19T20:42:17.000000", "ended_at": null, "state": "stopped", "uptime": 3500418}, {"hours": 1.111111111111111e-09, "flavor": "c2.m16", "instance_id": "4ba940c8-9f2d-4160-a07a-9a4123895237", "name": "g41zr00001864-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 16384, "local_gb": 0, "vcpus": 2, "started_at": "2021-03-22T15:30:26.000000", "ended_at": null, "state": "active", "uptime": 840729}, {"hours": 1.111111111111111e-09, "flavor": "36bafb7617af2c5cc4b7f64fb251dede", "instance_id": "5cc3311e-c2f1-4958-aa08-2e198f00e914", "name": "rhel83ks", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2021-03-18T15:07:44.000000", "ended_at": null, "state": "active", "uptime": 1187691}, {"hours": 1.111111111111111e-09, "flavor": "c1.m4", "instance_id": "63010b2c-2e97-44b9-9f52-f45c53679d14", "name": "g41zr00001838-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2021-03-18T17:22:45.000000", "ended_at": null, "state": "active", "uptime": 1179590}, {"hours": 1.111111111111111e-09, "flavor": "36bafb7617af2c5cc4b7f64fb251dede", "instance_id": "aa3d8f78-d3cb-44cd-9bc8-3205277f36c2", "name": "g41zr00002020-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 4096, "local_gb": 0, "vcpus": 1, "started_at": "2020-12-14T22:26:19.000000", "ended_at": null, "state": "active", "uptime": 9282976}, {"hours": 1.111111111111111e-09, "flavor": "c1.m16", "instance_id": "fc92fba3-b5b4-46b1-b4f1-ebf5e7a68b97", "name": "g41zr00001879-dev", "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac", "memory_mb": 16384, "local_gb": 0, "vcpus": 1, "started_at": "2021-03-25T22:05:16.000000", "ended_at": null, "state": "active", "uptime": 557839}], "total_local_gb_usage": 0.0, "total_vcpus_usage": 2.444444444444444e-08, "total_memory_mb_usage": 0.00016383999999999998, "total_hours": 1.9999999999999997e-08, "start": "2021-04-01T09:02:35.444222", "stop": "2021-04-01T09:02:35.444226"}}

**Comment by alexeymyltsev** [comment]
Thank you for output. 
You have duplicate records for instances, for example this one:
```                
              {
                    "hours": 1.111111111111111e-9,
                    "flavor": "c2.m4",
                    "instance_id": "09a0c811-a252-459a-9444-afe2d937710f",
                    "name": "g41zr00001682-dev",
                    "tenant_id": "39a2a73b8c6740f5982ce2d237f912ac",
                    "memory_mb": 4096,
                    "local_gb": 0,
                    "vcpus": 2,
                    "started_at": "2021-02-19T16:49:58.000000",
                    "ended_at": null,
                    "state": "active",
                    "uptime": 3514357
                }
```
May be you have some duplicates in DB. Did you migrate or restore your DB? 
From my point of view all records for instances should be unique.

Anyway, we did tests on our cluster and we saw that data from ```/os-simple-tenant-usage``` does not provide real data. Could you check ```/os-simple-tenant-usage``` for you VM with ephemeral disks? 
May be would be right remove this metric.

Just in case, information about ephemeral disks we collect with libvirt-exporter.

**Comment by emarins** [comment]
Hello @alexeymyltsev

Thank you for your reply.  Our OpenStack server was installed from scratch and the virtual servers were created using the web interface.  So, I really do not know why it is reporting duplicated. I can try to talk to the product developers to see if they can find something about the duplicated record.  I will let you know the response from them.

Our Openstack server is managing an IBM Z machine (mainframe) and we have two types of disks (DASD/ECKD and SAN disks).   The DASD disks are for OS and the SAN disks are for additional space (application data). 

Is there a way in the code to ignore the duplicated records ?  Of course, it does not fix the the problem, but it will allow us to start the openstack explorer.

I will keep you posted when I received a feedback from our Openstack developers about the duplicated records,

Thank you again

**Comment by alexeymyltsev** [comment]
It is possible to remove duplications in code, but I think would be easier remove this metric at all.
This metric collecting from field ```local_gb``` of ```/os-simple-tenant-usage```.
Could you check ```/os-simple-tenant-usage``` for you VMs?
Does it show useful information for you?

> Is there a way in the code to ignore the duplicated records ? Of course, it does not fix the the problem, but it will allow us to start the openstack explorer.

For start using openstack-exporter you can just disable this metric.

**Comment by emarins** [comment]
Because I am using DASD/ECKD disks the local_gb  metric is showing zero for all tenants.

"local_gb": 0

But it is really a good metric to get from Openstack.  We have plans in future to move OS disks from DASD/ECKD to SAN(SCSI), however it will take time and some planning to perform this migration.

**Comment by emarins** [comment]
Hello @alexeymyltsev ,

I have received the following reply from our Development team.
-------
we tested locally and have same output to yours, so it's an issue , I suspect it might be related to some bug in openstack U release (currently it's W which is U + 2 now) but no proof found so far because the code we are using is pure upstream and others don't have duplicate record and DB doesn't have duplicate record as well
 
my proposal is to follow below and do modifications at mgmt node only (add 2 lines in red) and
service openstack-nova-api restart to restart the service
then give a try if you want to keep the metrics , I tested locally at least it works and provide unique output
 
edit /usr/lib/python3.6/site-packages/nova/api/openstack/compute/simple_tenant_usage.py and

def _get_instances_all_cells(self, context, period_start, period_stop,
                                 tenant_id, limit, marker):
        all_instances = []
        cells = objects.CellMappingList.get_all(context)
        for cell in cells:
            with nova_context.target_cell(context, cell) as cctxt:
                if cell.uuid == '00000000-0000-0000-0000-000000000000':   ==> those 2 are newly added
                    continue                                              ==》

I believe the problem was found.   Thank you so much for your support!

**Comment by alexeymyltsev** [comment]
@emarins great that problem is found. 
Could you try this command?
```nova-manage cell_v2 list_hosts```
Looks like you have same hosts in two cells.

**Comment by emarins** [comment]
Hello,

The command did not show any output.

# nova-manage cell_v2 list_hosts
+-----------+-----------+----------+
| Cell Name | Cell UUID | Hostname |
+-----------+-----------+----------+
+-----------+-----------+----------+

After the update from development team.  everything seems working as expected now.

**Comment by alexeymyltsev** [comment]
I am not sure that patching is good solution.
I think you should check deeper you cells configurations.

Anyway I think this issue can be closed.

**Comment by emarins** [comment]
Thanks @alexeymyltsev ,  yes it can be closed!  Thanks again!
