### ISSUE TITLE
[Feature Request] change/add Metric openstack_cinder_volume

### ISSUE THREAD

**Issue by brolga** [openstack-exporter/openstack-exporter#180]
​​​​​The cinder volume metric ist exported as such:

```
openstack_cinder_volume_status
{
Region="RegionOne",
bootable="true",
id="173f7b48-c4c1-70-9acc-086b39073506",
name="test-volume",
size="1",
status="available",
tenant_id="bab7d5c60cd041a0a36f7c4b6e1dd978",
volume_type="lvmdriver-1",
server_id="f4fda93b-06e0-4743-8117-bc8bcecd651b"	
}
4.0 (float)
```

I propose the following change to this metric:

**Encode the status inside a label and not as a metric value.
Encode the volume size not as a Label but in the metric value.
Rename the metric to openstack_cinder_volume** 

This would enable the following prometheus queries, that are not easily possible with the current metric:

-  get the amount of volumestorage with a certain state
sum(openstack_cinder_volume{status="maintenance})

- get the count of volumes by a certain status and display status in cleartext
count(openstack_cinder_volume)by(status)

- sum up the amount volumestorage by tenant and volumetype
sum(openstack_cinder_volume)by(tenant_id,volume_type)

-  get the amount of volumes in errorstate
count(openstack_cinder_volume(status=~"error.*"}

Imho the ability to use this kind of queries would by very handy for resource management dashboards and also prometheus alarming.

**Comment by alexeymyltsev** [comment]
Hi @brolga ,
Your suggestion looks reasonable and I have created PR for it but I worry about people who already use openstack_cinder_volume(like me).
Additionally I changed name to volume_gb, it should be self explanatory for value.

@niedbalski what do you think about this change?

**Comment by brolga** [comment]
The suffix `_gb` is perfect for me.

A new Feature in 2 hours that solves my need ;-)

Very impresive, thank you very  much !

**Comment by niedbalski** [comment]
@alexeymyltsev @brolga I think the addition is very reasonable and I am in favor of the change. However, I dislike very much the idea of deprecating a metric without further notice in a new release.

I will post comments in pr #181 on how I think we could improve this change to make it have a minor impact for
the users upgrading.

**Comment by brolga** [comment]
I think it es reasonable add a new metric name and keep the original one laso in place.
