### ISSUE TITLE
malformed listen address causes panic

### ISSUE THREAD

**Issue by papaburgs** [openstack-exporter/openstack-exporter#194]
logs from journalctl
```
Jun 04 14:44:56 host openstack-exporter[25299]: panic: runtime error: index out of range [0] with length 0
Jun 04 14:44:56 host openstack-exporter[25299]: goroutine 1 [running]:
Jun 04 14:44:56 host openstack-exporter[25299]: github.com/openstack-exporter/openstack-exporter/exporters.IP4or6(0x7ffd37996df8, 0x7, 0x1, 0xb24a40)
Jun 04 14:44:56 host openstack-exporter[25299]: /app/exporters/utils.go:193 +0x1a7
Jun 04 14:44:56 host openstack-exporter[25299]: main.main()
Jun 04 14:44:56 host openstack-exporter[25299]: /app/main.go:89 +0x84c
```

I tried running with an invalid listen address (a problem with quoting)

Would expect it to fail, but at least log what was incorrect

**Comment by alexeymyltsev** [comment]
Hello @papaburgs.
Thank you for your report. 
Could you share example for problem reproduction?

**Comment by papaburgs** [comment]
Anything that doesn't match the regex will cause this, for example:
```
./openstack-exporter --multi-cloud --web.listen-address=""
```
or using "9888". 

I think the re.FindAllStrings is returning nil in that case, which causes the panic when it tries to be refrerenced.
I wouldn't expect it it succeed with an empty string, but at least log what the issue is.
