### ISSUE TITLE
Missing metrics when used with Wallaby release

### ISSUE THREAD

**Issue by JamesGibo** [openstack-exporter/openstack-exporter#204]
After upgrading to Openstack Wallaby some metrics seem to be missing, I have not looked at all metrics but have spotted the following are missing so far:
- openstack_nova_vcpus_available
- openstack_nova_vcpus_used

I believe this is because the API endpoint data you were using has been deprecated  
https://docs.openstack.org/nova/latest/reference/api-microversion-history.html#maximum-in-wallaby

**Comment by JamesGibo** [comment]
Apologies I see that you have added support for the placement API which includes this data.
https://github.com/openstack-exporter/openstack-exporter/commit/c7383a46f22c838a8063d4e5c6fdf33c57ba69e7

Are you planning on making a new release shortly? If not will build from source. 

Thanks for the exporter!

**Comment by niedbalski** [comment]
Hello @JamesGibo 

I will do a release this week. I hope that works for you.

**Comment by JamesGibo** [comment]
@niedbalski any chance you would be able to do a release this week? Would make deployment much easier for me, thanks.

**Comment by Sudermoni** [comment]
Kindly update the updated image details if any for the above ?

**Comment by Sudermoni** [comment]
can we get anyway the metrics running_vms? which is disabled from wallaby
