### ISSUE TITLE
Openstack osapi_max_limit

### ISSUE THREAD

**Issue by gabrielbatir** [openstack-exporter/openstack-exporter#22]
Hi

In Opensack the default value for osapi_max_limit is 1000 (The maximum number of items that a collection resource returns in a single response). Because of this limit openstack-exporter only gets info about the first 1000 instances, volumes, etc.

```
openstack_nova_total_vms{region="nova"} 1000.0
openstack_cinder_volumes{region="nova"} 1000.0
```

I have tested with quay.io/niedbalski/openstack-exporter-linux-amd64 master  5d5ec3eae5e0

**Comment by niedbalski** [comment]
@gabrielbatir Please check the latest image from master. We have switched to the gophercloud library instead of goose and paginated results should be available now.

docker pull quay.io/niedbalski/openstack-exporter-linux-amd64:master

Please let me know if this indeed fixes your issue.

**Comment by gabrielbatir** [comment]
Hi @niedbalski 
Just tried and I can see all the items past the 1000 limit so this issue is fixed.
I just noticed that openstack_cinder_snapshots is 0. It looks like it does not query for all tenants snapshots.  Do you want me to open another issue for this?

Thank you.

**Comment by niedbalski** [comment]
@gabrielbatir I've added the parameters required for listing all tenants snapshots. Please confirm if current master works for you so I can close this ticket.

Thank you

**Comment by gabrielbatir** [comment]
Hi.

Tested latest container image and all tenants snapshots count works.
Thank you.

**Comment by niedbalski** [comment]
@gabrielbatir alright, many thanks for contributing. I've added you to the CONTRIBUTORS section.
