### ISSUE TITLE
Provide binary builds for v1.5.0

### ISSUE THREAD

**Issue by priteau** [openstack-exporter/openstack-exporter#222]
I see that Docker images for v1.5.0 are available on Quay. Would it be possible to provide binary builds on GitHub too, like you did for previous releases? Thanks!

**Comment by priteau** [comment]
@niedbalski?

**Comment by frittentheke** [comment]
If I may add that the 1.5.0 milestone seems a little out of sync - https://github.com/openstack-exporter/openstack-exporter/milestone/16 as there already is a release. Also there are not release notes.

**Comment by niedbalski** [comment]
Hello @priteau , can you look at this issue?

**Comment by priteau** [comment]
The tarballs release failed because the VERSION file was not bumped, which caused it to try to overwrite 1.4.0 tarballs: https://app.circleci.com/pipelines/github/openstack-exporter/openstack-exporter/461/workflows/1eb05f22-a7bc-484a-95e6-16e54063f8e8/jobs/1342

**Comment by tgerczei** [comment]
FWIW there's no 1.6.0 build either.

**Comment by tgerczei** [comment]
FWIW there's no 1.6.0 build either.

**Comment by niedbalski** [comment]
https://github.com/openstack-exporter/openstack-exporter/releases/tag/v1.6.0
