### ISSUE TITLE
VERSION file not updated

### ISSUE THREAD

**Issue by priteau** [openstack-exporter/openstack-exporter#224]
The `VERSION` file still contains `1.4.0` despite `1.5.0` being released.

**Comment by jvleminc** [comment]
And this blocks the generation of the tarballs on github. :-(
Cf. https://github.com/openstack-exporter/openstack-exporter/issues/222#issuecomment-1062704414

**Comment by niedbalski** [comment]
https://github.com/openstack-exporter/openstack-exporter/issues/233#issuecomment-1153249519
