### ISSUE TITLE
Feature: Add option to include resource tags

### ISSUE THREAD

**Issue by max06** [openstack-exporter/openstack-exporter#230]
Greetings!

We make extensive use of tags for all kind of resources, like for users, projects and so on. It would be awesome if those tags could be included in the exported metrics.

Happy to take any other hint allowing us to reach a similar goal.

**Comment by n2N8Z** [comment]
"We make extensive use of tags for all kind of resources" - but this issue was closed after updating the metric for just one resource.

**Comment by n2N8Z** [comment]
https://wiki.openstack.org/wiki/InstanceTags - "Allow tags (arbitrary key-value pairs) to be attached to instances" - but it should be for all resources, not just instances.
When you have this, as in AWS, then you can do per tag usage reporting, and expense monitoring.
In the interim, without key/value tags, I'm hoing to embed key/values in the tag list instead, and then explode those out into prometheus labels.
