### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by Eli-Tarrago** [openstack-exporter/openstack-exporter#231]
1. Can you please tag the lastest version to include the lastest openstack nova and cinder api changes in wallaby?

2. Snap appears to be running 1.4 or 1.5, but doesn't include the latest openstack api changes.

3 Despite the documentation update, `https://quay.io/repository/niedbalski/openstack-exporter-linux-amd64?tab=tags` does not have a 1.6 release.

4. finally, I'm getting this error when im trying to build the library using make.

```
~/openstack-exporter# make common-build
>> building binaries
GO111MODULE= /root/go/bin/promu build --prefix /root/openstack-exporter
 >   openstack-exporter
../go/src/github.com/openstack-exporter/openstack-exporter/exporters/exporter.go:13:2: cannot find package "github.com/prometheus/common/log" in any of:
	/usr/lib/go-1.10/src/github.com/prometheus/common/log (from $GOROOT)
	/root/go/src/github.com/prometheus/common/log (from $GOPATH)
!! command failed: build -o /root/openstack-exporter/openstack-exporter -ldflags -X github.com/prometheus/common/version.Version=1.6.0 -X github.com/prometheus/common/version.Revision=59ded6d101bead6e38eaa42dd7d08c5adcac729b -X github.com/prometheus/common/version.Branch=master -X github.com/prometheus/common/version.BuildUser=root@bctlposad01 -X github.com/prometheus/common/version.BuildDate=20220517-15:12:53  -extldflags '-static' github.com/openstack-exporter/openstack-exporter: exit status 1
Makefile.common:226: recipe for target 'common-build' failed
make: *** [common-build] Error 1
```

I confirmed `https://github.com/prometheus/common` does indeed no longer exist.

**Comment by Eli-Tarrago** [comment]
Okay, here is future me with all the problems solved.

Above i was compiling against 1.6, you need to compile against prometheus common log of 0.7.0. IDK why in that earlier attempt the depens version were wrong. 

finally, I was able to fix the >Wallaby unable to talk to nova issue. I set the environment variable `OS_COMPUTE_API_VERSION=2.87`

Here is my systemd unit as an example.

```
[Unit]
Description=openstack-exporter
After=network.target

StartLimitIntervalSec=500
StartLimitBurst=5

[Service]
#ExecStart=/snap/bin/golang-openstack-exporter.openstack-exporter --os-client-config /root/openstack-exporter/clouds.yaml --multi-cloud --disable-slow-metrics
ExecStart=/root/openstack-exporter --os-client-config /root/openstack-exporter/clouds.yaml --multi-cloud --disable-service.image
KillMode=process
Restart=on-failure
RestartSec=5s
Environment=OS_COMPUTE_API_VERSION=2.87
[Install]
WantedBy=multi-user.target
```

**Comment by niedbalski** [comment]
Should be buildable by now https://github.com/openstack-exporter/openstack-exporter/issues/233#issuecomment-1153249519
