### ISSUE TITLE
When I get the metrics it returns the following errors

### ISSUE THREAD

**Issue by ivanovic90** [openstack-exporter/openstack-exporter#247]
Hello,

When I launch Openstack-exporter, it returns the following errors, I have Openstack Wallaby and Openstack-exporter version 1.6:

- level=error msg="Failed to collect metric for exporter: nova, error: failed to collect metric: security_groups, error: Resource not found: [GET http://10.24.4.50:8774/v2.1/os-security-groups], error message: {\"itemNotFound\": {\"code\": 404, \"message\": \"The resource could not be found.\"}}" source="exporter.go:124"

- level=error msg="Failed to collect metric for exporter: nova, error: failed to collect metric: running_vms, error: CPUInfo has unexpected type: <nil>" source="exporter.go:124"

- level=error msg="enabling exporter for service dns failed: No suitable endpoint could be found in the service catalog." source="main.go:174"

- level=error msg="enabling exporter for service baremetal failed: No suitable endpoint could be found in the service catalog." source="main.go:174"

- level=error msg="enabling exporter for service object-store failed: No suitable endpoint could be found in the service catalog." source="main.go:174"

- level=error msg="enabling exporter for service container-infra failed: No suitable endpoint could be found in the service catalog." source="main.go:174"

- level=error msg="enabling exporter for service gnocchi failed: No suitable endpoint could be found in the service catalog." source="main.go:174"

- level=error msg="enabling exporter for service database failed: No suitable endpoint could be found in the service catalog." source="main.go:174"

How can I fix these errors?

Thank you,
Regards

**Comment by alexeymyltsev** [comment]
Hello, @ivanovic90 
You can disable this metric 
```--disable-metric=nova-security_groups```

**Comment by ivanovic90** [comment]
Hello @alexeymyltsev ,
Thanks, although that only fixes the error: 

- level=error msg="Failed to collect metric for exporter: nova, error: failed to collect metric: security_groups, error: Resource not found: [GET http://10.24.4.50:8774/v2.1/os-security-groups], error message: {"itemNotFound": {"code": 404, "message": "The resource could not be found."}}" source="exporter.go:124"

But the rest of the errors continue to appear

**Comment by alexeymyltsev** [comment]
you can use ```--disable-service.dns --disable-service.baremetal  --disable-service.object-store --disable-service.container-infra --disable-service.gnocchi --disable-service.database``` 
 
And for CPU you can try this env ```OS_COMPUTE_API_VERSION=2.87```

**Comment by ivanovic90** [comment]
Thanks @alexeymyltsev ,
Where do I have to put this configuration "OS_COMPUTE_API_VERSION=2.87"?
Because I have put it in the file "clouds.yaml" but I still get the same error.

**Comment by alexeymyltsev** [comment]
it is env you should can use it as ```OS_COMPUTE_API_VERSION=2.87 ./openstack-exporter  --disable-service.dns --disable-service.baremetal --disable-service.object-store --disable-service.container-infra --disable-service.gnocchi --disable-service.database default```

**Comment by ivanovic90** [comment]
Thank you very much @alexeymyltsev , it already shows me all the metrics.
