### ISSUE TITLE
image failed: unable to load clouds.yaml: no clouds.yaml

### ISSUE THREAD

**Issue by shqnayaz** [openstack-exporter/openstack-exporter#248]
Hi 
Please help resolving the issue,

I have cloned the latest version and performed docker build.
Running the built image, 
but when i curl the localhost it says unable to load clouds.yaml.
The file does exist in all three places, 

Current Directory
~/.config/openstack
/etc/openstack

`
```

root@monitor-prome01  # docker run -d -v "$HOME/.config/openstack/clouds.yml":/etc/openstack/clouds.yaml -it -p 9180:9180 ghcr.io/openstack-exporter/openstack-exporter:latest --multi-cloud


Unable to find image 'ghcr.io/openstack-exporter/openstack-exporter:latest' locally
latest: Pulling from openstack-exporter/openstack-exporter
7d883a3eb1c5: Already exists
ac950f8db016: Already exists
8446b8a5a9ef: Already exists
Digest: sha256:932c9e6411a3a557e6fb35e6a582b4aee869ee7e46aa75570a3ac81f71083cb3
Status: Downloaded newer image for ghcr.io/openstack-exporter/openstack-exporter:latest
6cd16d1d2f35d617d9db3e198898721f8ab5eb418817d9ef31dcac2bef7127dc

root@monitor-prome01  # docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED         STATUS         PORTS                                           NAMES
6cd16d1d2f35   ghcr.io/openstack-exporter/openstack-exporter:latest   "/bin/openstack-expo…"   4 seconds ago   Up 3 seconds   0.0.0.0:9180->9180/tcp, :::9180->9180/tcp       xenodochial_chaum
```
```

# curl "http://localhost:9180/probe?cloud=openstack" -v
* About to connect() to localhost port 9180 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9180 (#0)
> GET /probe?cloud=openstack HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:9180
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; version=0.0.4; charset=utf-8
< Date: Wed, 10 Aug 2022 11:52:57 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
```

```
# docker logs -f 6cd16d1d2f35
INFO[0000] Build context (go=go1.18.3, user=, date=)     source="main.go:63"
INFO[0000] openstack exporter started in multi cloud mode (/probe?cloud=)  source="main.go:85"
INFO[0000] Starting HTTP server on :9180                 source="main.go:106"
INFO[0021] Enabled services: [network volume identity object-store image load-balancer container-infra dns placement compute database baremetal gnocchi orchestration]  source="main.go:140"
ERRO[0021] enabling exporter for service network failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0021] enabling exporter for service image failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0021] enabling exporter for service load-balancer failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0021] enabling exporter for service container-infra failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0021] enabling exporter for service dns failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"

^C

```

`

**Comment by shqnayaz** [comment]
Build with ghcr.io/openstack-exporter gives the above error, 

and clonning the master code built gives the below error.


root@monitor-prome01 ~ # docker ps |grep openstack
60c6e7093db5   openstack_exporter:latest     "/bin/openstack-expo…"   13 hours ago   Up 13 hours   0.0.0.0:9180->9180/tcp, :::9180->9180/tcp       openstack_exporter
root@monitor-prome01 ~ # docker logs  60c6e7093db5 |tail -n 15
INFO[45042] Enabled services: [container-infra database placement orchestration compute volume load-balancer gnocchi dns baremetal network image identity object-store]  source="main.go:140"
ERRO[45042] enabling exporter for service container-infra failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service database failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service placement failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service orchestration failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service compute failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service volume failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service load-balancer failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service gnocchi failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service dns failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service baremetal failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service network failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service image failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service identity failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"
ERRO[45042] enabling exporter for service object-store failed: unable to load clouds.yaml: no clouds.yaml file found  source="main.go:145"

**Comment by alexeymyltsev** [comment]
hello @shqnayaz 
Looks like you should debug you container. 
Can you ran it with ```/bin/sleep 60``` and check is there ```clouds.yaml``` in ```/etc/openstack/clouds.yaml``` ?

**Comment by srelf-eschercloud** [comment]
I had this issues, and it was due to an incorrectly set region name.

**Comment by shqnayaz** [comment]
Hi @alexeymyltsev , files are indeed present with additional prevelge just to ensure its readable by others as well.

root@monitor-prome01 ~ # ls -ltr .config/openstack/clouds.yaml
-rw-r-xr-x 1 root root 911 Aug  9 14:08 .config/openstack/clouds.yaml

root@monitor-prome01 ~ # ls -ltr /etc/openstack/clouds.yaml
-rw-r-xr-x 1 root root 941 Aug 10 13:11 /etc/openstack/clouds.yaml

and as well as cwd of openstack- exporter.

@srelf-eschercloud , 
appreciate if you can describe more about where the region name must be corrected.

**Comment by srelf-eschercloud** [comment]
Sure sorry, in the clouds.yaml file, i had a section for RegionName, i removed it and my issues went away. Its not needed, unless your running multi-region openstack.

My working file looks like this

https://pastebin.com/RSqt6pZb

**Comment by shqnayaz** [comment]
Thank you @srelf-eschercloud , that was a half relief. 
 My Clouds.yaml is as Yours. 
after removing region from clouds.yaml file.

Here are the results, 
Running openstack-exporter on command-line works.
./openstack-exporter --os-client-config /etc/openstack/clouds.yaml --multi-cloud
curl "http://localhost:9180/probe?cloud=openstack"


But
running as docker container it still reports, 
, 
# docker run -d -v "$HOME/.config/openstack/clouds.yml":/etc/openstack/clouds.yaml -it -p 9180:9180 ghcr.io/openstack-exporter/openstack-exporter:latest --multi-cloud

# docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS          PORTS                                           NAMES
6825f4db7625   ghcr.io/openstack-exporter/openstack-exporter:latest   "/bin/openstack-expo…"   30 seconds ago   Up 29 seconds   0.0.0.0:9180->9180/tcp, :::9180->9180/tcp       gallant_einstein

# docker logs  6825f4db7625
INFO[0000] Build context (go=go1.18.3, user=, date=)     source="main.go:63"
INFO[0000] openstack exporter started in multi cloud mode (/probe?cloud=)  source="main.go:85"
INFO[0000] Starting HTTP server on :9180                 source="main.go:106"
INFO[0024] Enabled services: [network compute dns identity container-infra baremetal database placement image volume load-balancer gnocchi object-store orchestration]  source="main.go:140"
ERRO[0024] enabling exporter for service network failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0024] enabling exporter for service compute failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0024] enabling exporter for service dns failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0024] enabling exporter for service identity failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"


appreciate your advice.

**Comment by srelf-eschercloud** [comment]
ah, yes, the final hurdle. 

try  docker run -d -v "$HOME/.config/openstack/clouds.yml/clouds.yaml":/etc/openstack/clouds.yaml -it -p 9180:9180 ghcr.io/openstack-exporter/openstack-exporter:latest --multi-cloud

**Comment by shqnayaz** [comment]
Yeah its same as above, unable to load clouds.yaml

```
# docker run -d -v "$HOME/.config/openstack/clouds.yml":/etc/openstack/clouds.yaml -it -p 9180:9180 ghcr.io/openstack-exporter/openstack-exporter:latest --multi-cloud

# docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS          PORTS                                           NAMES
6825f4db7625   ghcr.io/openstack-exporter/openstack-exporter:latest   "/bin/openstack-expo…"   30 seconds ago   Up 29 seconds   0.0.0.0:9180->9180/tcp, :::9180->9180/tcp       gallant_einstein

# docker logs  6825f4db7625
INFO[0000] Build context (go=go1.18.3, user=, date=)     source="main.go:63"
INFO[0000] openstack exporter started in multi cloud mode (/probe?cloud=)  source="main.go:85"
INFO[0000] Starting HTTP server on :9180                 source="main.go:106"
INFO[0024] Enabled services: [network compute dns identity container-infra baremetal database placement image volume load-balancer gnocchi object-store orchestration]  source="main.go:140"
ERRO[0024] enabling exporter for service network failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0024] enabling exporter for service compute failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0024] enabling exporter for service dns failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"
ERRO[0024] enabling exporter for service identity failed: unable to load clouds.yaml: read /etc/openstack/clouds.yaml: is a directory  source="main.go:145"

```

**Comment by shqnayaz** [comment]
Hi @srelf-eschercloud , 
Sorry my Bad, I had a typo error on the docker command.

I had these name conflict, 
```
# ls -l ~/.config/openstack/
total 4
-rw-r-xr-x 1 root root 364 Aug 15 13:53 clouds.y**a**ml
drwxr-xr-x 3 root root  24 Aug 15 13:52 clouds.yml

```
So earlier in docker run command it was pointing to clouds.yml which is actually a directory itself and wasn't able to read.

it worked.
`# docker run -d -v "$HOME/.config/openstack/clouds.yaml":/etc/openstack/clouds.yaml -it -p 9180:9180 ghcr.io/openstack-exporter/openstack-exporter:latest --multi-cloud
`

**Comment by shqnayaz** [comment]
Thank you so much
