### ISSUE TITLE
enabling exporter for service volumev3 failed: error when authenticating: cannot create service URLs

### ISSUE THREAD

**Issue by cszhi** [openstack-exporter/openstack-exporter#25]
ERRO[0000] enabling exporter for service volumev3 failed: error when authenticating: cannot create service URLs
caused by: the configured region "RegionTwo" does not allow access to all required services, namely: volumev3
access to these services is missing: volumev3  source="main.go:63"

**Comment by niedbalski** [comment]
@cszhi can you make sure that your tenant is able to reach the volumev3 endpoint for the regiontwo?

**Comment by niedbalski** [comment]
I am closing this bug, as I haven't received confirmation from you that the error wasn't a configuration issue.

Please feel free to re-open it at any given time if you are reproducing this issue.

Thank you!
