### ISSUE TITLE
Use gophercloud instead of goose

### ISSUE THREAD

**Issue by alistarle** [openstack-exporter/openstack-exporter#26]
The go Openstack SDK used for many project like terraform or packer is [gophercloud](https://github.com/gophercloud/gophercloud), it count more than 3k commits, and is actively used by the community with 600+ issue and 350+ stars.

Indeed, more or less all the openstack actions are present in gophercloud, whereas goose lacks a lot of thing (by example aggregate host in order to return it on many hypervisors metrics). It also provide built in reading of clouds.yaml by example

`clientconfig.GetCloudFromYAML(clientOpts)`

So it really simplify the code of the exporter

I suggest to migrate to gophercloud in order to be able to add new feature more easily and to use more supported backend library.

**Comment by alistarle** [comment]
BTW I begin to work on that and already migrate half of the metrics to gophercloud, I will make a draft PR when all will be migrated.

**Comment by niedbalski** [comment]
@alistarle I am ok with your proposal, If you could draft a PR that we can follow up, it would be really helpful.

**Comment by alistarle** [comment]
Thanks, here is the draft, it works but there is still a lot of work to do : https://github.com/openstack-exporter/openstack-exporter/pull/27

**Comment by niedbalski** [comment]
@alistarle Thank you much. Could you please review the comment on #27? Please rebase on top of the gophercloud branch and re-submit, lets work from there rather than master.

Thanks again for your work on this!

**Comment by niedbalski** [comment]
@alistarle  Please check #30 for a continuation work on your original PR.

**Comment by niedbalski** [comment]
I am closing this bug as no other feedback has been provided. Feel free to open a new issue if you find any bug or missing implementation.

Thanks!

**Comment by alistarle** [comment]
Sorry I was not available these days, but thanks for merging this code ! I will test this week then add some metrics I was looking for for moving to gophercloud
