### ISSUE TITLE
I don’t understand what’s wrong with this error report, please let me know, thank you

### ISSUE THREAD

**Issue by alexclownfish** [openstack-exporter/openstack-exporter#269]
I don’t understand what’s wrong with this error report, please let me know, thank you
![image](https://user-images.githubusercontent.com/63449830/212022916-c4c54c25-8ad6-4ad3-ab5a-1a83ca32b833.png)

**Comment by alexclownfish** [comment]
This is my configuration, using version 1.6.0
![image](https://user-images.githubusercontent.com/63449830/212027346-7aad7bf1-31a4-4f58-8790-59f773902f7e.png)

**Comment by qq346434990** [comment]
startup parameter 'RegionOne' replace 'default'
