### ISSUE TITLE
[Feature Request] Add IP Address Label To Neutron Port

### ISSUE THREAD

**Issue by alirezarm78** [openstack-exporter/openstack-exporter#289]
Hello.
I hope that we have fixed_ip_address label for neutron port metric, we really need it.
Thank you.

**Comment by odnobit** [comment]
@niedbalski I can take this task.

**Comment by odnobit** [comment]
Hello @alirezarm78!
I'm waiting for my neutron PR review and merge to avoid conflicts.

**Comment by alirezarm78** [comment]
Hello dear @odnobit 
In your PR i can't see anything about this feature request
Can you explain it?

**Comment by odnobit** [comment]
> Hello dear @odnobit In your PR i can't see anything about this feature request Can you explain it?

Sure. I'm waiting when my current PR will be merged because conflicts are possible. And then I will start working for your requested feature.

**Comment by odnobit** [comment]
yea, sure
