### ISSUE TITLE
Any new binary releases

### ISSUE THREAD

**Issue by Knalltuete5000** [openstack-exporter/openstack-exporter#299]
I just wanted to ask if there are any plans to release any new binary releases on top of the docker images.

The latest binary release is over 1 year old and there were many changes included since then.

**Comment by berendt** [comment]
As a project (OpenStack Kolla & OSISM) we are dependent on being able to consume release tags. Would it be possible to make a new release so that we can deliver more current versions?

Related to https://github.com/osism/issues/issues/808

**Comment by berendt** [comment]
@niedbalski Please see if this is possible in a reasonable time. At least in Kolla, the OpenStack exporter used is very old and can no longer be used with OpenStack 2023.1 (Antelope).

**Comment by niedbalski** [comment]
> @niedbalski Please see if this is possible in a reasonable time. At least in Kolla, the OpenStack exporter used is very old and can no longer be used with OpenStack 2023.1 (Antelope).

Sure, I will do a release this week.

**Comment by berendt** [comment]
> Sure, I will do a release this week.

Cool. Thanks for the quick response!

**Comment by frittentheke** [comment]
@niedbalski may I nag you once more about a new release? 

With new OpenStack releases and the corresponding API changes upgrades to the exporter are required (Antelope already breaks it, as @berendt already stated).

**Comment by berendt** [comment]
@frittentheke Thanks for the ping.

That would be great, yes. We're currently preparing our next release with OpenStack 2023.2 and it would be nice if the exporter would work again there. We need a release tag there to consume the exporter binary.

**Comment by priteau** [comment]
@niedbalski Any chance you could tag a new release soon? Thanks.

**Comment by berendt** [comment]
We (OSISM) are shortly before the next release (20 March) and are currently doing the pre-releases. If nothing comes by the end of the week, we would create a fork for us for the moment and set up a tag there in order to be able to deliver a current version with the next release of OSISM.

**Comment by niedbalski** [comment]
> We forked to https://github.com/osism/openstack-exporter and threw out everything we didn't need ourselves (snap, container, ...), updated a few versions and made a tag on it. We don't want to continue maintaining it there and would be happy if it continues here. It is only intended as a workaround for the tag + some newer versions.

Cool, will make sure to do a new release over here. Will be happy if somebody with a good track record else wants to step up as maintainer.

**Comment by niedbalski** [comment]
https://github.com/openstack-exporter/openstack-exporter/releases/tag/v1.7.0
