### ISSUE TITLE
'GLIBC_2.34' error after go version update: 1.19 -> 1.22

### ISSUE THREAD

**Issue by curveds** [openstack-exporter/openstack-exporter#339]
After recent update of go version Docker caught the error: 

`/bin/openstack-exporter: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.34' not found (required by /bin/openstack-exporter)`

**Comment by frittentheke** [comment]
@niedbalski  ... could you maybe create a 1.7.1 release with the build using Golang 1.22
