### ISSUE TITLE
Add aggregate information to nova metrics

### ISSUE THREAD

**Issue by alistarle** [openstack-exporter/openstack-exporter#34]
Now we are using Gophercloud, we are able to add more complex metrics, I think adding the missing "aggregate" information will be a good start

**Comment by niedbalski** [comment]
Hello @alistarle 

I've commented in your PR #35 , I would like to include your changes into 0.6.0, but I need your feedback on the code.

**Comment by niedbalski** [comment]
@alistarle I'll move this for 0.7.0 so we can test it properly and merge a better PR.

**Comment by alistarle** [comment]
No problem, I will try to fix the PR this weekend

**Comment by niedbalski** [comment]
OK, this has been merged as part of #35 , Thank you very much @alistarle , I'll add you to the list of contributors.
