### ISSUE TITLE
[Feature Request] Cache mechanism

### ISSUE THREAD

**Issue by jneo8** [openstack-exporter/openstack-exporter#351]
relate to: #214 

We propose introducing an optional caching feature to the exporter to address slow queries, which can be activated as follows:

```
# Cache metrics by name
openstack-exporter --cached-metrics=AAA,BBB

# Cache metrics by service 
openstack-exporter --cached-services=AAA,BBB

# Global cache
openstack-exporter --cached --cached-ttl 60s
```

This feature would entail a background process that collects metrics every 5 minutes (customizable) and stores them in a file or memory. Cached values would be returned upon Prometheus scraping, provided the cache is ready.

We're eager to assist with its implementation but seek the maintainer's approval on whether this would be a valuable addition.

> Note: Our main purpose is to have a cache mechanism, so not necessarily implemented as described above

**Comment by fprzewozny** [comment]
That would be cool!

**Comment by jneo8** [comment]
Hi Christian. Thanks for your feedback. I want to make sure we are on the same page here.

> But if the exporter was to collect all the data independently from the Prometheus scraping I suggest to also introduce some kind of worker pattern to split up the collection of all those metrics.

When you mention about `split up the collection of all those metrics`, what is the granularity here? We separate by the service and run query parallel? Or you want to have a more small granularity(which means re-write the collector)?

I think we can limit the scope here, we still use the same collector and provide a cache here. The collector optimization can be another issue. How do you think?

(We also thinking about the scaling problem, so it's nice if we can make it scalable)
