### ISSUE TITLE
Exporter crashes when collecting compute metrics

### ISSUE THREAD

**Issue by uxeng** [openstack-exporter/openstack-exporter#37]
Looks like _openstack_nova_agent_state_ is a metric that contains metadata that does not change over time (e.g. hostname). exporter does not handle this metric properly?

After running the exporter for few seconds/minutes, this error is shown when trying to collect the metrics (e..g wget http:/xxx:port/metrics)
 

An error has occurred while serving metrics:

collected metric "openstack_nova_agent_state" { label:<name:"adminState" value:"enabled" > label:<name:"hostname" value:"XXXXXXX" > label:<name:"service" value:"nova-conductor" > label:<name:"zone" value:"internal" > counter:<value:1 > } was collected before with the same name and label values

**Comment by niedbalski** [comment]
@uxeng which version are you using? can you include the full logs?

**Comment by uxeng** [comment]
Same errors using both snap versions edge and stable. 

$ openstack --version
openstack 4.0.0

I dont see any errors on the console:

.........
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching domains information                  source="keystone.go:50"
INFO[0017] Collecting metrics for exporter: openstack_cinder, metric: snapshots  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching snapshots information                source="cinder.go:116"
INFO[0017] Collecting metrics for exporter: openstack_neutron, metric: security_groups  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching list of network security groups      source="neutron.go:127"
INFO[0017] Collecting metrics for exporter: openstack_cinder, metric: agent_state  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching services state information           source="cinder.go:136"
INFO[0017] Collecting metrics for exporter: openstack_identity, metric: users  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching users information                    source="keystone.go:112"
INFO[0017] Collecting metrics for exporter: openstack_cinder, metric: volume_status  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Collecting metrics for exporter: openstack_neutron, metric: subnets  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching list of subnets                      source="neutron.go:147"
INFO[0017] Collecting metrics for exporter: openstack_neutron, metric: ports  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching list of ports                        source="neutron.go:167"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: running_vms  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching list of hypervisors                  source="nova.go:118"
INFO[0017] Collecting metrics for exporter: openstack_neutron, metric: agent_state  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching agents list                          source="neutron.go:75"
INFO[0017] Collecting metrics for exporter: openstack_neutron, metric: floating_ips  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching floating ips list                    source="neutron.go:56"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: vcpus_available  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: memory_used_bytes  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: flavors  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching list of flavors                      source="nova.go:161"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: availability_zones  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching list of availability zones           source="nova.go:182"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: current_workload  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: vcpus_used  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: local_storage_used_bytes  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: security_groups  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching list of nova security groups         source="nova.go:202"
INFO[0017] Collecting metrics for exporter: openstack_nova, metric: agent_state  source="exporter.go:69"
INFO[0017] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0017] Fetching list of services                     source="nova.go:92"
INFO[0018] Collecting metrics for exporter: openstack_nova, metric: memory_available_bytes  source="exporter.go:69"
INFO[0018] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0018] Collecting metrics for exporter: openstack_nova, metric: local_storage_available_bytes  source="exporter.go:69"
INFO[0018] Refreshing auth client in case token has expired  source="exporter.go:85"
INFO[0018] Collecting metrics for exporter: openstack_nova, metric: server_status  source="exporter.go:69"
INFO[0018] Refreshing auth client in case token has expired  source="exporter.go:85"
.....

**Comment by niedbalski** [comment]
PR #40 should have fixed this issue by appending the service.ID to the list of labels. Please test it and let me know if it works as expected. @uxeng

**Comment by niedbalski** [comment]
Are you able to reproduce this further with the latest master @uxeng ?

**Comment by uxeng** [comment]
Hi,
issue is fixed!!!
thank you very much :) 

/U
