### ISSUE TITLE
Authentification failed from exporter to Openstack

### ISSUE THREAD

**Issue by noor47-pixel** [openstack-exporter/openstack-exporter#379]
hello i am using openstack version 16.2 with prometheus-openstack exporter v 1.7 and podman 

The solution is running on podman container then i have also a conf file: clouds.yaml;

Problem 
i got this error  Authentifcation failed from every service,

ts=2024-07-19T12:07:57.143Z caller=main.go:170 level=info msg="Build context" build_context="(go=go1.18.10, platform=linux/amd64, user=, date=, tags=unknown)"
ts=2024-07-19T12:07:57.146Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:57.424Z caller=main.go:184 level=error err="enabling exporter for service failed" service=object-store error="Authentication failed"
ts=2024-07-19T12:07:57.425Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:57.703Z caller=main.go:184 level=error err="enabling exporter for service failed" service=database error="Authentication failed"
ts=2024-07-19T12:07:57.704Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:57.954Z caller=main.go:184 level=error err="enabling exporter for service failed" service=container-infra error="Authentication failed"
ts=2024-07-19T12:07:57.955Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:58.226Z caller=main.go:184 level=error err="enabling exporter for service failed" service=baremetal error="Authentication failed"
ts=2024-07-19T12:07:58.227Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:58.491Z caller=main.go:184 level=error err="enabling exporter for service failed" service=placement error="Authentication failed"
ts=2024-07-19T12:07:58.492Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:58.759Z caller=main.go:184 level=error err="enabling exporter for service failed" service=network error="Authentication failed"
ts=2024-07-19T12:07:58.759Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:59.010Z caller=main.go:184 level=error err="enabling exporter for service failed" service=compute error="Authentication failed"
ts=2024-07-19T12:07:59.011Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:59.270Z caller=main.go:184 level=error err="enabling exporter for service failed" service=image error="Authentication failed"
ts=2024-07-19T12:07:59.270Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:59.525Z caller=main.go:184 level=error err="enabling exporter for service failed" service=orchestration error="Authentication failed"
ts=2024-07-19T12:07:59.526Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:07:59.795Z caller=main.go:184 level=error err="enabling exporter for service failed" service=volume error="Authentication failed"
ts=2024-07-19T12:07:59.796Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:08:00.052Z caller=main.go:184 level=error err="enabling exporter for service failed" service=identity error="Authentication failed"
ts=2024-07-19T12:08:00.053Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:08:00.325Z caller=main.go:184 level=error err="enabling exporter for service failed" service=load-balancer error="Authentication failed"
ts=2024-07-19T12:08:00.326Z caller=exporter.go:205 level=info msg="SSL verification disabled on transport"
ts=2024-07-19T12:08:00.602Z caller=main.go:184 level=error err="enabling exporter for service failed" service=gnocchi error="Authentication failed"
ts=2024-07-19T12:08:00.602Z caller=main.go:194 level=error err="No exporter has been enabled, exiting"
ts=2024-07-19T12:08:00.934Z caller=main.go:64 level=info msg="Build context" build_context="(go=go1.18.10, platform=linux/amd64, user=, date=, tags=unknown)"
ts=2024-07-19T12:08:00.934Z caller=main.go:85 level=info msg="openstack exporter started in legacy mode"
ts=2024-07-19T12:08:00.935Z caller=tls_config.go:274 level=info msg="Listening on" address=[::]:9180
ts=2024-07-19T12:08:00.935Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9180
Verification 
- my access are all ok login password and i don't also have an network issue

Anybody have an idea of what causes this problem ?

**Comment by noor47-pixel** [comment]
@niedbalski Any Idea ?

**Comment by Jonher937** [comment]
Verify your credentials and that they can successfully be used to authenticate against the cloud from where you are running the exporter.

The error is clearly `error="Authentication failed"` and since it's from all service, it means it's not only a permission issue, but an authentication or connectivity issue.

This could also happen if there is a HTTP_PROXY passed into the container, as it will try to inherit it from the systems config and hit something else via the proxy that is not a openstack cloud.

**Comment by noor47-pixel** [comment]
thank u for your feedback i'm gonna check this point in my clouds.yml file
