### ISSUE TITLE
General interest in helping with overall maintainership; v2 migration

### ISSUE THREAD

**Issue by jayofdoom** [openstack-exporter/openstack-exporter#381]
Hi, I'm Jay Faulkner, I'm a long-time Ironic contributor, OpenStack TC member, and Open Source Developer with G-Research Open Source Software.

We have interest in helping migrate the openstack-exporter to v2, and overall assisting with the ongoing maintenance of this project. Our developer, Adam McArthur (@sharpz7), has some time assigned, but we wanted to get positive affirmation from you all that you'd be willing to merge PRs migrating to v2, and overall willing to accept additional external contribution.

This would be part of a larger effort to ensure more fields we desire are exported, with a specific focus on Ironic-related metrics.

Thanks in advance,
JayF

**Comment by niedbalski** [comment]
@jayofdoom we are willing to accept additional external contributions and review and dedicate time to it.

**Comment by Jonher937** [comment]
I was looking at the docs for v2 migration today and dropping this link here so that it's not overlooked: https://github.com/gophercloud/gophercloud/blob/master/docs/MIGRATING.md

**Comment by jayofdoom** [comment]
Thanks; going to close this. Feel free to reach out if there's anything specific we can do to help -- especially me, with my upstream-openstack hat on :D.
