### ISSUE TITLE
Document Microversion behaviour 

### ISSUE THREAD

**Issue by Sharpz7** [openstack-exporter/openstack-exporter#409]
From our work in https://github.com/openstack-exporter/openstack-exporter/pull/378, it wasn't immediately clear that Openstack-Exporter supported openstack's older than fields it explicitly references. This is likely to come up in the future more and more as new fields are added.

We should document openstack-exporter behaves fine in these scenarios, defaulting to the "false" state (or something like that for other types)

This could be in a section like "Operational Notes" or "Admin Considerations"

**Comment by jayofdoom** [comment]
:+1: LGTM, this matches our testing with an older ironic microversion

This should be good to merge @niedbalski
