### ISSUE TITLE
error in installation of  v 0.6.0

### ISSUE THREAD

**Issue by gammohamed** [openstack-exporter/openstack-exporter#47]
- ### **Error when  start the service as below::::**

gamal@Openstack-Pike:/tmp/openstack-exporter-0.6.0.linux-amd64$ sudo systemctl status openstack-exporter
sudo: unable to resolve host Openstack-Pike
● openstack-exporter.service - openstack exporter
   Loaded: loaded (/etc/systemd/system/openstack-exporter.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-10-24 00:00:53 EET; 5s ago
  Process: 15900 ExecStart=/usr/local/bin/openstack-exporter (code=exited, status=1/FAILURE)
 Main PID: 15900 (code=exited, status=1/FAILURE)

Oct 24 00:00:53 Openstack-Pike systemd[1]: Started openstack exporter.
Oct 24 00:00:53 Openstack-Pike systemd[1]: openstack-exporter.service: Main process exited, code=exited, status=1/FA
Oct 24 00:00:53 Openstack-Pike systemd[1]: openstack-exporter.service: Unit entered failed state.
Oct 24 00:00:53 Openstack-Pike systemd[1]: openstack-exporter.service: Failed with result 'exit-code'.

**### Installation steps  is :** 

sudo useradd --no-create-home --shell /bin/false openstack-exporter

cd openstack-exporter-0.6.0.linux-amd64/

sudo mv openstack-exporter   /usr/local/bin/

sudo chown openstack-exporter:openstack-exporter /usr/local/bin/openstack-exporter

sudo vim /etc/systemd/system/openstack-exporter.service

[Unit]
Description=openstack exporter
After=network.target

[Service]
User=openstack-exporter
Group=openstack-exporter
Type=simple
ExecStart=/usr/local/bin/openstack-exporter

[Install]
WantedBy=multi-user.target

---
sudo systemctl daemon-reload

sudo systemctl start openstack-exporter

**Comment by gammohamed** [comment]
gamal@Openstack-Pike:/usr/local/bin$ openstack-exporter
openstack-exporter: error: required argument 'cloud' not provided, try --help
gamal@Openstack-Pike:/usr/local/bin$ openstack-exporter ?
INFO[0000] Starting openstack exporter version (version=, branch=, revision=) for cloud: ?  source="main.go:38"
INFO[0000] Build context (go=go1.11.13, user=, date=)    source="main.go:39"
ERRO[0000] enabling exporter for service network failed: cloud ? does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service compute failed: cloud ? does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service image failed: cloud ? does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service volume failed: cloud ? does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service identity failed: cloud ? does not exist in clouds.yaml  source="main.go:51"
INFO[0000] Starting HTTP server on :9180                 source="main.go:72"

**Comment by niedbalski** [comment]
Hello @gammohamed 

You need to pass the cloud name (as described in your clouds.yaml) as the first parameter to the command, I.e. openstack-exporter cloud.region.org 

Please let me know if you have any other issue.

Thanks

**Comment by gammohamed** [comment]
**### gamal@Openstack-Pike:/usr/local/bin$ cat /etc/openstack/clouds.yaml**
clouds:
  devstack:
    auth:
      auth_url: http://192.168.43.16/identity
      password: secret
      project_domain_id: default
      project_name: demo
      user_domain_id: default
      username: demo
    identity_api_version: '3'
    region_name: RegionOne
    volume_api_version: '2'
  devstack-admin:
    auth:
      auth_url: http://192.168.43.16/identity
      password: secret
      project_domain_id: default
      project_name: admin
      user_domain_id: default
      username: admin
    identity_api_version: '3'
    region_name: RegionOne
    volume_api_version: '2'
  devstack-alt:
    auth:
      auth_url: http://192.168.43.16/identity
      password: secret
      project_domain_id: default
      project_name: alt_demo
      user_domain_id: default
      username: alt_demo
    identity_api_version: '3'
    region_name: RegionOne
    volume_api_version: '2'

**Comment by gammohamed** [comment]
**$ openstack-exporter --os-client config="/etc/openstack/clouds.yaml"  RegionOne**

INFO[0000] Starting openstack exporter version (version=, branch=, revision=) for cloud: RegionOne  source="main.go:38"
INFO[0000] Build context (go=go1.11.13, user=, date=)    source="main.go:39"
ERRO[0000] enabling exporter for service image failed: cloud RegionOne does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service volume failed: cloud RegionOne does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service identity failed: cloud RegionOne does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service network failed: cloud RegionOne does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service compute failed: cloud RegionOne does not exist in clouds.yaml  source="main.go:51"
INFO[0000] Starting HTTP server on :9180                 source="main.go:72"
FATA[0000] listen tcp :9180: bind: address already in use  source="main.go:73"

**Comment by niedbalski** [comment]
./openstack-exporter --os-client config="/etc/openstack/clouds.yaml" devstack
./openstack-exporter --os-client config="/etc/openstack/clouds.yaml" devstack-alt

**Comment by gammohamed** [comment]
**$ openstack-exporter      --os-client-config="/etc/openstack/clouds.yaml"  main**

INFO[0000] Starting openstack exporter version (version=, branch=, revision=) for cloud: main  source="main.go:38"
INFO[0000] Build context (go=go1.11.13, user=, date=)    source="main.go:39"
ERRO[0000] enabling exporter for service volume failed: No suitable endpoint could be found in the service catalog.  source="main.go:51"
ERRO[0000] enabling exporter for service identity failed: No suitable endpoint could be found in the service catalog.  source="main.go:51"
ERRO[0000] enabling exporter for service network failed: No suitable endpoint could be found in the service catalog.  source="main.go:51"
ERRO[0000] enabling exporter for service compute failed: No suitable endpoint could be found in the service catalog.  source="main.go:51"
ERRO[0000] enabling exporter for service image failed: No suitable endpoint could be found in the service catalog.  source="main.go:51"
INFO[0000] Starting HTTP server on :9180                 source="main.go:72"
FATA[0000] listen tcp :9180: bind: address already in use  source="main.go:73"

**Comment by gammohamed** [comment]
if did the clouds.yml , and run service with RegionOne  and main  ... as posted in the previous comments ... but still error .

**Comment by gammohamed** [comment]
> ./openstack-exporter --os-client config="/etc/openstack/clouds.yaml" devstack
> ./openstack-exporter --os-client config="/etc/openstack/clouds.yaml" devstack-alt

**Comment by gammohamed** [comment]
**same Error as below**
**$ ./openstack-exporter --os-client config="/etc/openstack/clouds.yaml"  devstack**

INFO[0000] Starting openstack exporter version (version=, branch=, revision=) for cloud: devstack  source="main.go:38"
INFO[0000] Build context (go=go1.11.13, user=, date=)    source="main.go:39"
ERRO[0000] enabling exporter for service image failed: cloud devstack does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service volume failed: cloud devstack does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service identity failed: cloud devstack does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service network failed: cloud devstack does not exist in clouds.yaml  source="main.go:51"
ERRO[0000] enabling exporter for service compute failed: cloud devstack does not exist in clouds.yaml  source="main.go:51"
INFO[0000] Starting HTTP server on :9180                 source="main.go:72"
FATA[0000] listen tcp :9180: bind: address already in use  source="main.go:73"
