### ISSUE TITLE
openstack-exporter installation

### ISSUE THREAD

**Issue by gammohamed** [openstack-exporter/openstack-exporter#5]
For openstack-exporter installation ,
1- is it only in dockers or it is available in "binaries&configration file" ?
2-what is the other installation methods ?

**Comment by mikejoh** [comment]
It is available as a single binary or a binary packaged in a Docker container. In the case of a single binary i guess you could create e.g. a systemd service to run it as a system process and not through Docker.

Both of these options are mentioned in the readme but not any other deployment methods (as running it via e.g. systemd).

I guess that would be fairly easy to write though!

**Comment by niedbalski** [comment]
@gammohamed thanks for your interest on this project.

The project is shipped as a binary for arm64 and amd64 , you can find the latest release here:

* https://github.com/openstack-exporter/openstack-exporter/releases/tag/v0.0.8

Also we produce docker images for the same architectures:

* https://quay.io/repository/niedbalski/openstack-exporter-linux-amd64?tab=tags
* https://quay.io/repository/niedbalski/openstack-exporter-linux-arm64?tab=tags

Please feel free to ask any questions you might have and I'll try to reply them
ASAP.

Thank you.

**Comment by gammohamed** [comment]
can you share with me the openstack-exporter installation guide for binary package deployment, for openstack  OOO project ?
