### ISSUE TITLE
Metrics Count 

### ISSUE THREAD

**Issue by gammohamed** [openstack-exporter/openstack-exporter#51]
**after installation i found only 12   metric scraped, as below , is it the right  number ?** 

![Capture](https://user-images.githubusercontent.com/50797995/67600673-d8f86280-f772-11e9-8b65-9d74b61d1b9e.JPG)

**Comment by niedbalski** [comment]
@gammohamed nope, you can check the total list of metrics in the README.md file, this looks like not all the exporters were enabled. Can you show me the output/logs for this exporter?
