### ISSUE TITLE
error in logs 

### ISSUE THREAD

**Issue by gammohamed** [openstack-exporter/openstack-exporter#52]
ERRO[0405] Request forbidden: [GET http://10.0.0.2/compute/v2.1/os-hypervisors/detail], error message: {"forbidden": {"message": "Policy doesn't allow os_compute_api:os-hypervisors to be performed.", "code": 403}}  source="nova.go:123"

ERRO[1094] Request forbidden: [GET http://10.0.0.2/volume/v2/20db7932a7bc424f9a322321660ef29b/os-services], error message: {"forbidden": {"message": "Policy doesn't allow volume_extension:services:index to be performed.", "code": 403}}  source="cinder.go:141"

**Comment by niedbalski** [comment]
Check the policy in use for the tenant. This has to be run with admin privileges.

**Comment by niedbalski** [comment]
Since this is not a direct bug of the exporter, I am closing this issue until having further information.

**Comment by bientt210** [comment]
Thanks for answer me @niedbalski ,

My problem has solved, cause be network connection. i'm close issue now, 
Thanks you so much for your support :)
