### ISSUE TITLE
Make network_ip_availabilities metric per subnet 

### ISSUE THREAD

**Issue by alistarle** [openstack-exporter/openstack-exporter#54]
In order to cover more use case (multiple subnets per network), I propose to process this metrics per subnet instead of per network.

As the information is already in API response, there is no overhead in term of API call, and there is no too much generated metrics as in case of a 1 subnet / 1 network model we will only generate one metric.

If we want to keep the metric processing per network, operator can just sum the generate metric per network.

**Comment by alistarle** [comment]
Covered in #53

**Comment by niedbalski** [comment]
LGTM @alistarle , merged.
