### ISSUE TITLE
Add ability to disable metric gathering

### ISSUE THREAD

**Issue by alistarle** [openstack-exporter/openstack-exporter#55]
In order to limit impact of the exporter againt large Openstack environment, it will be very usefull to be able to blacklist some metrics, by example the "openstack_nova_server_status" or the "openstack_cinder_volume_status".

We can take example on the node-exporter who use "--no-collector.<name>" argument, or using a configuration file.

**Comment by niedbalski** [comment]
@alistarle we have the '--disable-*exporter*' options, are you thinking something more granular per-metric?

**Comment by alistarle** [comment]
Yes, maybe a --disable-metric option so, because using this exporter in an deployment with Manu thousands of VM or volumes is impossible for now I think

**Comment by niedbalski** [comment]
@alistarle happy to review or work on this feature.

**Comment by niedbalski** [comment]
Hello @alistarle 

I have implemented this as part of #56, please let me know if that change is acceptable for you before proceeding to close this ticket.

Thanks!
