### ISSUE TITLE
Endpoint problem

### ISSUE THREAD

**Issue by mehrdadpfg** [openstack-exporter/openstack-exporter#57]
Hi there,

I have an openstack with separated internal and external endpoints. But the exporter cannot handle it and tries to connect to public endpoint. Is there any configuration needed?

**Comment by mehrdadpfg** [comment]
anybody?

**Comment by niedbalski** [comment]
@mehrdadpfg you can specify the identity_interface = { internal, public } in the clouds.yaml file.

**Comment by mehrdadpfg** [comment]
@niedbalski I had set the identity_interface but in retrieving data from keystone the identity_interface value is not set as the endpoint type for keystone so the public endpoint returns and causes the issue

**Comment by mehrdadpfg** [comment]
@niedbalski any update?

**Comment by toxick** [comment]
We're running into the same issue:

    # kubectl describe pod/openstack-exporter-6c8fff679c-vvmbw | grep Image:
    Image:         quay.io/niedbalski/openstack-exporter-linux-amd64:v0.7.0


    clouds.yaml:
    ---
    clouds:
      default:
        auth:
          auth_url: http://172.29.236.100:5000/v3
          project_name: admin
          tenant_name: admin
          username: admin
          password: [redacted]
          user_domain_name: Default
          project_domain_name: Default
        region_name: RegionOne
        identity_api_version: "3"
        identity_interface: internal


    # openstack endpoint list -c 'Service Name' -c Interface -c URL
    +--------------+-----------+---------------------------------------------+
    | Service Name | Interface | URL                                         |
    +--------------+-----------+---------------------------------------------+
    | placement    | admin     | http://172.29.236.100:8780                  |
    | cinderv2     | public    | http://<public-ip>:8776/v2/%(tenant_id)s    |
    | glance       | admin     | http://172.29.236.100:9292                  |
    | keystone     | admin     | http://172.29.236.100:5000                  |
    | cinderv2     | internal  | http://172.29.236.100:8776/v2/%(tenant_id)s |
    | placement    | public    | http://<public-ip>:8780                     |
    | placement    | internal  | http://172.29.236.100:8780                  |
    | neutron      | public    | http://<public-ip>:9696                     |
    | keystone     | internal  | http://172.29.236.100:5000                  |
    | keystone     | public    | http://<public-ip>:5000                     |
    | cinderv3     | admin     | http://172.29.236.100:8776/v3/%(tenant_id)s |
    | cinderv2     | admin     | http://172.29.236.100:8776/v2/%(tenant_id)s |
    | nova         | public    | http://<public-ip>:8774/v2.1                |
    | glance       | internal  | http://172.29.236.100:9292                  |
    | cinderv3     | public    | http://<public-ip>:8776/v3/%(tenant_id)s    |
    | neutron      | internal  | http://172.29.236.100:9696                  |
    | neutron      | admin     | http://172.29.236.100:9696                  |
    | cinderv3     | internal  | http://172.29.236.100:8776/v3/%(tenant_id)s |
    | nova         | admin     | http://172.29.236.100:8774/v2.1             |
    | nova         | internal  | http://172.29.236.100:8774/v2.1             |
    | glance       | public    | http://<public-ip>:9292                     |
    +--------------+-----------+---------------------------------------------+


    # kubectl logs openstack-exporter-6c8fff679c-vvmbw | grep timeout
    time="2019-11-13T20:38:30Z" level=error msg="Get http://<public-ip>:9696/v2.0/ports: dial tcp <public-ip>:9696: i/o timeout" source="neutron.go:178"
    time="2019-11-13T20:38:30Z" level=error msg="Get http://<public-ip>:5000/v3/users: dial tcp <public-ip>:5000: i/o timeout" source="keystone.go:117"
    time="2019-11-13T20:38:30Z" level=error msg="Get http://<public-ip>:8774/v2.1/os-security-groups: dial tcp <public-ip>:8774: i/o timeout" source="nova.go:240"
    time="2019-11-13T20:38:30Z" level=error msg="Get http://<public-ip>:8776/v2/4543b597efcd45f5b079c1c9b277535c/volumes/detail?all_tenants=true: dial tcp <public-ip>:8776: i/o timeout" source="cinder.go:93"
    time="2019-11-13T20:38:30Z" level=error msg="Get http://<public-ip>:9292/v2/images: dial tcp <public-ip>:9292: i/o timeout" source="glance.go:50"
    time="2019-11-13T20:38:56Z" level=error msg="Get http://<public-ip>:9292/v2/images: dial tcp <public-ip>:9292: i/o timeout" source="glance.go:50"
    time="2019-11-13T20:38:56Z" level=error msg="Get http://<public-ip>:8774/v2.1/os-hypervisors/detail: dial tcp <public-ip>:8774: i/o timeout" source="nova.go:131"
    time="2019-11-13T20:38:56Z" level=error msg="Get http://<public-ip>:5000/v3/domains: dial tcp <public-ip>:5000: i/o timeout" source="keystone.go:55"
    time="2019-11-13T20:38:56Z" level=error msg="Get http://<public-ip>:9696/v2.0/networks: dial tcp <public-ip>:9696: i/o timeout" source="neutron.go:118"
    time="2019-11-13T20:38:57Z" level=error msg="Get http://<public-ip>:8776/v2/4543b597efcd45f5b079c1c9b277535c/volumes/detail?all_tenants=true: dial tcp <public-ip>:8776: i/o timeout" source="cinder.go:93"
    time="2019-11-13T20:39:00Z" level=error msg="Get http://<public-ip>:9696/v2.0/floatingips: dial tcp <public-ip>:9696: i/o timeout" source="neutron.go:67"
    time="2019-11-13T20:39:00Z" level=error msg="Get http://<public-ip>:9696/v2.0/floatingips: dial tcp <public-ip>:9696: i/o timeout" source="neutron.go:67"
    time="2019-11-13T20:39:00Z" level=error msg="Get http://<public-ip>:5000/v3/domains: dial tcp <public-ip>:5000: i/o timeout" source="keystone.go:55"
    time="2019-11-13T20:39:00Z" level=error msg="Get http://<public-ip>:5000/v3/groups: dial tcp <public-ip>:5000: i/o timeout" source="keystone.go:136"
    time="2019-11-13T20:39:00Z" level=error msg="Get http://<public-ip>:9292/v2/images: dial tcp <public-ip>:9292: i/o timeout" source="glance.go:50"
    time="2019-11-13T20:39:00Z" level=error msg="Get http://<public-ip>:8774/v2.1/os-security-groups: dial tcp <public-ip>:8774: i/o timeout" source="nova.go:240"
    time="2019-11-13T20:39:00Z" level=error msg="Get http://<public-ip>:8776/v2/4543b597efcd45f5b079c1c9b277535c/os-services: dial tcp <public-ip>:8776: i/o timeout" source="cinder.go:141"
    time="2019-11-13T20:39:00Z" level=error msg="Get http://<public-ip>:8776/v2/4543b597efcd45f5b079c1c9b277535c/snapshots?all_tenants=true: dial tcp <public-ip>:8776: i/o timeout" source="cinder.go:121"
    time="2019-11-13T20:39:01Z" level=error msg="Get http://<public-ip>:8774/v2.1/os-hypervisors/detail: dial tcp <public-ip>:8774: i/o timeout" source="nova.go:131"


Exporter is attempting to connect to public endpoints rather than the internal endpoints.

**Comment by niedbalski** [comment]
@toxick @mehrdadpfg Since gophercloud utils for clientconfig doesn't support parsing the identity-type option we are exposing the --endpoint-type parameter that defaults to public.

Now you should be able to specify the enpodint-type parameter as:

./openstack-exporter --endpoint-type internal cloud-name 

Please let me know if this works for your use case.

Thanks

**Comment by toxick** [comment]
@niedbalski Yep, that works for me!  Thanks for the quick turnaround!

Will there be another image released for this update?

**Comment by niedbalski** [comment]
It is in master already, will be released as part of 0.8.0 soon.

**Comment by mehrdadpfg** [comment]
@niedbalski i added a part to utils.go to handle this i will make a pull request for that
