### ISSUE TITLE
Drastically increase exporter performance

### ISSUE THREAD

**Issue by alistarle** [openstack-exporter/openstack-exporter#60]
From the migration to gophercloud, I figured out the scrape duration time jump from 2sec to more than 7sec, even in a devstack environment.

I achieve to plug some jaeger tracing inside the exporter to find what's happening especially in term of API call, and here is what I found.

![image](https://user-images.githubusercontent.com/4499513/68966449-652fff80-07de-11ea-99c6-6221aaa40d35.png)

For every metric we gather we call the refresh client function, which basically call the
`exporter.Client.Reauthenticate(exporter.Client.Token()` function, and take aproximatly 300ms to achieve, this clearly break the exporter efficiency.

If I comment the call of this function in the `CollectMetrics` function, here is the new trace:

![image](https://user-images.githubusercontent.com/4499513/68966634-e091b100-07de-11ea-864c-d86399a08434.png)

It is nearly 10times less longer !! And the scrape duration is only occupied by the real API call to openstack services. We clearly need to fix that.

I will try to work on that in the future days, and try to commit my code to add opentracing to the exporter, it can be usefull in the future to detect any regression like that.

**Comment by alistarle** [comment]
As we can see in the gophercloud code (https://github.com/gophercloud/gophercloud/blob/master/provider_client.go#L431). The Reauthenticate function is called automatically in case of a Unauthorized exception during request, so I think we can just remove this part of the code and let gophercloud do the reauthenticate when needed.

**Comment by mnaser** [comment]
FWIW this is closed by #62 and will be released with #64

**Comment by niedbalski** [comment]
Merged , Thanks
