### ISSUE TITLE
Release v0.8.0

### ISSUE THREAD

**Issue by mnaser** [openstack-exporter/openstack-exporter#64]
Hi there,

There was recently a change merged which helped with performance which impacts us a lot at scale.

Can we release v0.8.0 ? :)

Thanks,
Mohammed

**Comment by niedbalski** [comment]
Hello @mnaser 

Sure. We have a couple of issues that I'd like to solve before releasing [0]. If we can't solve them before this Friday, I will make a release by then.

Does that works for you?

[0] https://github.com/openstack-exporter/openstack-exporter/milestone/7

**Comment by mnaser** [comment]
Sounds good to me!

FWIW: we started rolling this out in production and alerting based on it.

We can publish a helm chart soon as well. 

Thanks,
Mohammed

**Comment by niedbalski** [comment]
@mnaser 

I am delighted to hear that. Out of curiosity. What are you using for deploying? We've been 
pushing the releases to kolla-ansible regularly.

Thanks for letting me know!

**Comment by mnaser** [comment]
@niedbalski We have written up Helm charts which leverages the `prometheus-operator`, so with `PrometheusRule` and `ServiceMonitor`.

I'm thinking perhaps it would be good to contribute it to helm/charts -- or we can have it here in our own repos inside `openstack-exporter/helm-charts` or something.

**Comment by niedbalski** [comment]
@mnaser done, added openstack-exporter/helm-charts and made you admin of that group. Feel free to push the chars there and I'll make sure to create a deployment section under the README file that points to it.

Many thanks for your contribution.

**Comment by mnaser** [comment]
@niedbalski 

all done, with circleci publishing things too.  i'll have to get around adding a readme, but it's pretty uh, straightforward.

not very flexible but it's a start.
