### ISSUE TITLE
exporter crashing when trying to reach the metrics

### ISSUE THREAD

**Issue by vaibhavjayas** [openstack-exporter/openstack-exporter#7]
time="2019-06-13T14:03:46Z" level=info msg="Fetching volumes info" source="cinder.go:54"
time="2019-06-13T14:03:46Z" level=error msg="Get /volumes: Get /volumes: unsupported protocol scheme \"\"" source="cinder.go:57"
time="2019-06-13T14:03:46Z" level=info msg="Fetching services state information" source="cinder.go:60"
time="2019-06-13T14:03:46Z" level=error msg="Get /os-services: Get /os-services: unsupported protocol scheme \"\"" source="cinder.go:63"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x82827d]

goroutine 61 [running]:
main.(*CinderExporter).Collect(0xc000180580, 0xc00016d7a0)
        /app/cinder.go:66 +0x1dd
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x193
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /app/vendor/github.com/prometheus/client_golang/prometheus/registry.go:445 +0x590

**Comment by mikejoh** [comment]
Hi @vaibhavjayas,

Could you somehow verify, in your configuration file passed to `openstack-exporter`, that you use the correct `region_name` for your OpenStack environment?

The only way i can think of that this could happen is when the region name is wrong and the `endpoint` variable is empty here:

https://github.com/openstack-exporter/openstack-exporter/blob/35b2bcb65c87fb5cf8154547dd98290ccd9973ca/cinder.go#L24

I managed to reproduce it by setting `config.Region` (in the above method call) to something different from what we use in our environment and i got back the exact same error messages.
