### ISSUE TITLE
CinderAgentState doesn't support HA deployments - duplicates error

### ISSUE THREAD

**Issue by matuskosut** [openstack-exporter/openstack-exporter#84]
Openstack-exporter reports duplicates error when volume service is enabled. The issue is cause with the key openstack_cinder_agent_state.

For HA deployments of cinder it seems common to have same name and host, including all the other labels. Which doesn't cause any issue in openstack. Such setup is managed for example by Juju where these labels couldn't be set different.

Would it be possible to also include ID, as a label in these metrics, to avoid duplicates and failure of openstack-exporter?

```
An error has occurred while serving metrics:

2 error(s) occurred:
* collected metric "openstack_cinder_agent_state" { label:<name:"adminState" value:"enabled" > label:<name:"hostname" value:"cinder@ceph" > label:<name:"service" value:"cinder-volume" > label:<name:"zone" value:"nova" > counter:<value:0 > } was collected before with the same name and label values
* collected metric "openstack_cinder_agent_state" { label:<name:"adminState" value:"enabled" > label:<name:"hostname" value:"cinder@ceph" > label:<name:"service" value:"cinder-volume" > label:<name:"zone" value:"nova" > counter:<value:0 > } was collected before with the same name and label values
```

**Comment by niedbalski** [comment]
Should have been fixed by #80 , please check and report back if wasn't fixed.
