### ISSUE TITLE
Value of openstack_cinder_volume_status is unclear

### ISSUE THREAD

**Issue by larsks** [openstack-exporter/openstack-exporter#86]
What is the *value* of the `openstack_cinder_volume_status` metric? It varies between a number of integer values, but I'm unclear what they mean.  E.g.:

```
openstack_cinder_volume_status{bootable="false",id="...",name="...",size="1000",status="in-use",tenant_id="...",volume_type="performance"} 5
openstack_cinder_volume_status{bootable="false",id="...",name="...",size="100",status="available",tenant_id="...",volume_type="default"} 1
use",tenant_id="...",volume_type="default"} 5
openstack_cinder_volume_status{bootable="false",id="...",name="...",size="1",status="error",tenant_id="...",volume_type="default"} 9
openstack_cinder_volume_status{bootable="false",id="...",name="...",size="1",status="creating",tenant_id="...",volume_type="default"} 0
```

It looks like you're not exposing the volume size as a metric? I was hoping to calculate "top consumers of volume space by project", for example, which would require the volume size to be a value rather than a label.

**Comment by tzmtl** [comment]
It's the index of this list, 0 means "creating", 1 means "available", etc.

```
var volume_status = []string{
        "creating",
        "available",
        "reserved",
        "attaching",
        "detaching",
        "in-use",
        "maintenance",
        "deleting",
        "awaiting-transfer",
        "error",
        "error_deleting",
        "backing-up",
        "restoring-backup",
        "error_backing-up",
        "error_restoring",
        "error_extending",
        "downloading",
        "uploading",
        "retyping",
        "extending",
}
```

**Comment by niedbalski** [comment]
I hope your question has been answered. @tzmtl perhaps we should improve documentation on this front?

**Comment by whoamiUNIX** [comment]
+1 for this issue. It was also not clear for my. Thanks for this index. Would be great to include this in documentation.

**Comment by alexeymyltsev** [comment]
@niedbalski so far as PR has been merged, I think we can close this issue.

**Comment by alexeymyltsev** [comment]
PR add requested documentation to README.
