### ISSUE TITLE
can anyone share prometheus scrape config for openstack exporter 

### ISSUE THREAD

**Issue by abidahmeds** [openstack-exporter/openstack-exporter#88]
i am able to deploy exporter and i have a full fledged prom/Grafana system.

but i fail to get metrics into my grafana atleast. 

what else is needed for config of prom , i have below.

    - job_name: n71-adpteoam-openstack
      scrape_interval: 5m
      static_configs:
        - targets: ['10.98.80.11:9180']

**Comment by niedbalski** [comment]
As reference, that's the configuration being used in the kolla-ansible project https://github.com/openstack/kolla-ansible/blob/master/ansible/roles/prometheus/templates/prometheus.yml.j2#L78
